import { useState } from 'react';
import { Link } from 'react-router-dom';

const workflow = [
  ['01', 'Maintenance Data', 'Bring maintenance demand into one planning view.'], ['02', 'RiskClock', 'Identify risks requiring earlier attention.'], ['03', 'Priority Engine', 'Add operational context to maintenance demand.'], ['04', 'Block Bundler', 'Group compatible work into coordinated windows.'], ['05', 'Conflict Shield', 'Surface incompatible activities before planning.'], ['06', 'CP-SAT Optimization', 'Search feasible combinations under constraints.'], ['07', 'Simulation & Risk', 'Evaluate operational trade-offs under uncertainty.'], ['08', 'GATI Evaluation', 'Compare candidates through structured evaluation.'], ['09', 'Final Recommendation', 'Present a clear, explainable control plan.'],
];
const problems = [['◫', 'Fragmented demand', 'Maintenance requests across departments can be difficult to coordinate.'], ['⌘', 'Operational conflicts', 'Overlapping work, shared track sections, and limited windows require careful planning.'], ['◌', 'Uncertain outcomes', 'A plan must be evaluated for risk and possible disruption, not just duration.']];
const intelligence = [['Risk Intelligence', 'Surface maintenance risks and help prioritize attention.'], ['Constraint-based Optimization', 'Generate feasible candidate plans using structured planning constraints.'], ['Simulation & Evaluation', 'Explore how candidate plans may perform under uncertainty.'], ['Explainable AI', 'Translate complex planning outputs into understandable recommendations.']];
const benefits = [['Prioritize with context', 'Consider risk and operational importance, not severity alone.'], ['Coordinate across departments', 'Bring Engineering, SNT, and TRD maintenance demand into one planning view.'], ['Evaluate before deciding', 'Compare candidate plans using operational and risk-related metrics.'], ['Explain every recommendation', 'Make planning outputs easier for decision-makers to understand.']];

function Mark() { return <span className="landing-mark" aria-hidden="true"><i /><i /><i /></span>; }
function Arrow() { return <span aria-hidden="true">→</span>; }
function SectionHead({ eyebrow, title, children }) { return <div className="landing-head"><p className="landing-eyebrow">{eyebrow}</p><h2>{title}</h2>{children && <p>{children}</p>}</div>; }
function RailVisual() { return <div className="rail-visual" aria-label="Stylized railway planning map"><div className="visual-top"><span className="live-dot" /> NETWORK INTELLIGENCE <small>WESTERN CORRIDOR</small></div><svg viewBox="0 0 620 390" role="img" aria-label="Railway corridor with maintenance and operational signals"><defs><linearGradient id="railGlow" x1="0" x2="1"><stop stopColor="#27c8e8" stopOpacity=".18"/><stop offset=".5" stopColor="#27c8e8"/><stop offset="1" stopColor="#f3b74d" stopOpacity=".55"/></linearGradient></defs><path className="map-grid" d="M0 68H620M0 150H620M0 232H620M0 314H620M90 0V390M210 0V390M330 0V390M450 0V390M570 0V390"/><path className="route-shadow" d="M45 274C125 260 136 172 222 189S309 310 390 267 463 105 570 112"/><path className="route" d="M45 274C125 260 136 172 222 189S309 310 390 267 463 105 570 112"/><path className="route-alt" d="M221 189C287 142 367 150 420 188"/><g className="route-node"><circle cx="45" cy="274" r="9"/><circle cx="222" cy="189" r="9"/><circle cx="390" cy="267" r="9"/><circle cx="570" cy="112" r="9"/></g><g className="asset amber"><circle cx="291" cy="265" r="7"/><circle cx="291" cy="265" r="15"/></g><g className="asset cyan"><circle cx="468" cy="142" r="7"/><circle cx="468" cy="142" r="15"/></g><g className="asset cyan"><circle cx="132" cy="216" r="7"/><circle cx="132" cy="216" r="15"/></g><text x="28" y="303">DEPOT</text><text x="193" y="167">JUNCTION 4</text><text x="365" y="294">YARD</text><text x="533" y="91">TERMINAL</text></svg><div className="visual-card ai-card"><span className="card-label">AI PLANNING INTELLIGENCE</span><strong>Compatible window identified</strong><p><i /> Track section C · 02:00–04:30</p></div><div className="visual-card plan-card"><span className="card-label">RECOMMENDED PLAN</span><strong>Plan A <b>READY FOR REVIEW</b></strong><div><em /><em /><em /></div></div></div>; }

export function Landing() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  return <main className="landing"><nav className="landing-nav" aria-label="Main navigation"><Link className="landing-brand" to="/landing"><Mark /><strong>RAILVISTA</strong></Link><button className="landing-menu" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle menu"><i /><i /><i /></button><div className={menuOpen ? 'landing-links open' : 'landing-links'}><a href="#product" onClick={closeMenu}>Product</a><a href="#intelligence" onClick={closeMenu}>Intelligence</a><a href="#workflow" onClick={closeMenu}>Workflow</a><a href="#platform" onClick={closeMenu}>Platform</a><a href="#about" onClick={closeMenu}>About</a><Link className="nav-signin" to="/login" onClick={closeMenu}>Sign in</Link><Link className="nav-cta" to="/login" onClick={closeMenu}>Explore the platform <Arrow /></Link></div></nav>
    <section className="landing-hero" id="product"><div className="hero-copy"><p className="landing-eyebrow"><span className="live-dot" /> DECISION SUPPORT FOR RAILWAY OPERATIONS</p><h1>Smarter Railway Maintenance.<br /><span>Safer Operational Decisions.</span></h1><p className="hero-description">RAILVISTA connects maintenance demand, risk intelligence, conflict detection, optimization, and simulation into one decision-support workflow for railway operations.</p><div className="hero-actions"><Link className="landing-button primary-landing" to="/login">Explore the platform <Arrow /></Link><a className="landing-button secondary-landing" href="#workflow">See how it works <span>↓</span></a></div><div className="hero-note"><i /> From maintenance demand to an explainable control plan.</div></div><RailVisual /></section>
    <section className="positioning"><p>Built for coordinated railway maintenance planning</p><div><span>Risk-aware planning</span><span>Cross-department coordination</span><span>Constraint-based optimization</span><span>Explainable recommendations</span></div></section>
    <section className="landing-section problem-section" id="about"><SectionHead eyebrow="THE PLANNING CHALLENGE" title="Railway maintenance is more than a list of tasks.">Maintenance requests come from multiple departments, compete for limited work windows, and can affect train operations. A better planning process must understand risk, coordination, feasibility, and operational impact together.</SectionHead><div className="problem-grid">{problems.map(([icon, title, text]) => <article className="problem-card" key={title}><span className="line-icon">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="landing-section workflow-section" id="workflow"><SectionHead eyebrow="CONNECTED WORKFLOW" title="From maintenance requests to one informed plan.">RAILVISTA brings the planning process into a connected workflow that helps teams move from raw demand to an explainable operational recommendation.</SectionHead><div className="workflow-rail">{workflow.map(([number, title, text], index) => <article className="workflow-step" key={title}><span>{number}</span><div className="workflow-icon">{index === 8 ? '✓' : '◈'}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="landing-section intelligence-section" id="intelligence"><div><SectionHead eyebrow="PLANNING INTELLIGENCE" title="AI that supports decisions, not just predictions.">RAILVISTA combines predictive analysis, optimization, simulation, and generative AI to support complex railway planning decisions.</SectionHead><div className="intelligence-grid">{intelligence.map(([title, text], index) => <article className="intelligence-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><Arrow /></article>)}</div></div><div className="decision-flow"><p>PLANNING SIGNAL PATH</p>{['Data', 'Intelligence', 'Optimization', 'Evaluation', 'Decision'].map((item, index) => <div key={item}><b>{index + 1}</b><span>{item}</span>{index < 4 && <i />}</div>)}</div></section>
    <section className="landing-section preview-section" id="platform"><SectionHead eyebrow="PLATFORM VIEW" title="A unified view for the control room." /><div className="preview-shell"><div className="preview-sidebar"><Mark /><span>COMMAND</span><i /><i /><i /><i /></div><div className="preview-content"><div className="preview-top"><span>OPERATIONAL OVERVIEW</span><b><i /> SYSTEM READY</b></div><div className="preview-metrics"><div><small>NETWORK HEALTH</small><strong>Under review</strong><i /></div><div><small>MAINTENANCE DEMAND</small><strong>Coordinated view</strong><i /></div><div><small>CONTROL PLAN</small><strong>Recommendation</strong><i /></div></div><div className="preview-panels"><div className="preview-map"><small>CORRIDOR PLANNING VIEW</small><svg viewBox="0 0 450 150" aria-hidden="true"><path d="M8 121C110 100 99 37 191 58s71 77 149 37 67-55 102-38"/><circle cx="98" cy="79" r="6"/><circle cx="191" cy="58" r="6"/><circle cx="286" cy="91" r="6"/><circle cx="394" cy="43" r="6"/></svg></div><div className="recommendation"><small>RECOMMENDED CONTROL PLAN</small><strong>Evidence-backed alternative</strong><p><i /> Operational review ready</p><button>Review plan <Arrow /></button></div></div></div></div><p className="preview-caption">One platform for maintenance visibility, planning intelligence, and operational review.</p></section>
    <section className="landing-section benefits-section"><SectionHead eyebrow="WHY RAILVISTA" title="Designed for better maintenance coordination." /><div className="benefit-grid">{benefits.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="final-cta"><div><p className="landing-eyebrow">READY TO EXPLORE</p><h2>Turn maintenance data into informed operational decisions.</h2><p>Explore how RAILVISTA connects railway maintenance intelligence, planning, and evaluation in one platform.</p></div><Link className="landing-button primary-landing" to="/login">Explore RAILVISTA <Arrow /></Link></section>
    <footer className="landing-footer"><div><Link className="landing-brand" to="/landing"><Mark /><strong>RAILVISTA</strong></Link><p>An AI-powered decision-support platform for informed railway maintenance planning.</p></div><div className="footer-links"><a href="#product">Product</a><a href="#intelligence">Intelligence</a><a href="#workflow">Workflow</a><a href="#platform">Platform</a></div><small>Built for intelligent railway maintenance planning</small></footer>
  </main>;
}
