import { changePlanStatus, createPlan, deletePlan, getPlan, getWorkflowOverview, listAdminData, listAudit, listNotifications, listPlans, listTasks, markNotificationRead, updatePlan } from '../services/operationalService.js';
import { evidenceForPlan, transitionPlan } from '../services/workflowService.js';
const send = (req, res, data) => res.json({ data, meta: { requestId: req.id } });
export async function tasksController(req, res, next) { try { send(req, res, await listTasks(req.query)); } catch (error) { next(error); } }
export async function plansController(req, res, next) { try { send(req, res, await listPlans(req.params.runId, req.query)); } catch (error) { next(error); } }
export async function planController(req, res, next) { try { const plan = await getPlan(req.params.planId); if (!plan) return res.status(404).json({ type: 'about:blank', title: 'Not Found', status: 404, detail: 'Plan not found' }); send(req, res, plan); } catch (error) { next(error); } }
export async function createPlanController(req, res, next) { try { send(req, res, await createPlan(req.body)); } catch (error) { next(error); } }
export async function updatePlanController(req, res, next) { try { const plan = await updatePlan(req.params.planId, req.body); if (!plan) return res.status(409).json({ type: 'about:blank', title: 'Conflict', status: 409, detail: 'Only editable plans can be changed' }); send(req, res, plan); } catch (error) { next(error); } }
export async function deletePlanController(req, res, next) { try { const plan = await deletePlan(req.params.planId); if (!plan) return res.status(409).json({ type: 'about:blank', title: 'Conflict', status: 409, detail: 'Only draft plans can be deleted' }); send(req, res, plan); } catch (error) { next(error); } }
export async function statusController(req, res, next) { try { send(req, res, await transitionPlan(req.params.planId, req.body.status, req.user.sub, req.body.comment, req.id)); } catch (error) { next(error); } }
export async function notificationsController(req, res, next) { try { send(req, res, await listNotifications(req.user.sub, req.query)); } catch (error) { next(error); } }
export async function notificationReadController(req, res, next) { try { send(req, res, await markNotificationRead(req.params.notificationId, req.user.sub)); } catch (error) { next(error); } }
export async function adminController(req, res, next) { try { send(req, res, await listAdminData(req.params.type)); } catch (error) { next(error); } }
export async function auditController(req, res, next) { try { send(req, res, await listAudit(req.query)); } catch (error) { next(error); } }
export async function simulationController(req, res, next) { try { const [simulation] = await evidenceForPlan(req.params.planId); if (!simulation) return res.status(404).json({ type: 'about:blank', title: 'Not Found', status: 404, detail: 'Simulation result not found' }); send(req, res, simulation); } catch (error) { next(error); } }
export async function riskController(req, res, next) { try { const [, risk] = await evidenceForPlan(req.params.planId); if (!risk) return res.status(404).json({ type: 'about:blank', title: 'Not Found', status: 404, detail: 'Risk report not found' }); send(req, res, risk); } catch (error) { next(error); } }
export async function reportController(req, res, next) { try { const plan = req.query.planId ? await getPlan(req.query.planId) : null; const [, risk, approvals] = plan ? await evidenceForPlan(plan._id) : [null, null, []]; const report = { type: req.query.type || 'maintenance', generatedAt: new Date().toISOString(), plan, risk, approvals }; if (req.query.format === 'csv') { const rows = [['field', 'value'], ['type', report.type], ['planId', plan?._id || ''], ['gati', risk?.gati || ''], ['status', plan?.status || '']]; res.type('text/csv').attachment(`${report.type}-report.csv`).send(rows.map((row) => row.map((v) => `"${String(v).replaceAll('"', '""')}"`).join(',')).join('\n')); return; } send(req, res, report); } catch (error) { next(error); } }
export async function workflowOverviewController(req, res, next) { try { send(req, res, await getWorkflowOverview(req.query)); } catch (error) { next(error); } }
