import { Router } from 'express';
import { authenticate } from '../middleware/authenticate.js';
import { analyzeRiskController, explanationController, simulateController } from '../controllers/intelligenceController.js';
import { authorize } from '../middleware/authorize.js';
import { body } from 'express-validator';
import { validateRequest } from '../middleware/validateRequest.js';
import { adminController, auditController, createPlanController, deletePlanController, emergencyRepairController, notificationReadController, notificationsController, planController, plansController, reportController, riskController, simulationController, statusController, tasksController, updatePlanController, workflowOverviewController } from '../controllers/operationalController.js';

export const operationalRoutes = Router();
operationalRoutes.use(authenticate);
operationalRoutes.get('/tasks', tasksController);
operationalRoutes.get('/workflow/overview', workflowOverviewController);
operationalRoutes.post('/intelligence/simulations', simulateController);
operationalRoutes.post('/intelligence/risk-analysis', analyzeRiskController);
operationalRoutes.post('/intelligence/explanations', explanationController);
operationalRoutes.get('/planning-runs/:runId/plans', plansController);
operationalRoutes.get('/plans/:planId', planController);
operationalRoutes.get('/plans/:planId/simulations', simulationController);
operationalRoutes.get('/plans/:planId/risk', riskController);
operationalRoutes.post('/plans', createPlanController);
operationalRoutes.patch('/plans/:planId', updatePlanController);
operationalRoutes.delete('/plans/:planId', deletePlanController);
operationalRoutes.post('/plans/:planId/status', body('status').isIn(['RISKCLOCK_COMPLETE', 'BUNDLING_COMPLETE', 'CONFLICT_CHECKED', 'OPTIMIZED', 'SIMULATION_COMPLETE', 'APPROVED', 'PUBLISHED', 'ARCHIVED']), validateRequest, statusController);
operationalRoutes.post('/plans/:planId/emergency-repair', body('taskId').optional().isString(), emergencyRepairController);
operationalRoutes.get('/notifications', notificationsController);
operationalRoutes.post('/notifications/:notificationId/read', notificationReadController);
operationalRoutes.get('/reports', reportController);
operationalRoutes.get('/admin/:type', authorize('ADMIN', 'CONTROL_OFFICER'), adminController);
operationalRoutes.get('/audit-logs', authorize('ADMIN', 'CONTROL_OFFICER'), auditController);
