import { motion } from 'framer-motion';
import { useEffect, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { operationsApi } from '../../api/operationsApi.js';

const riskData = [{ name: 'Mean', value: 18 }, { name: 'P95', value: 41 }, { name: 'CVaR10', value: 56 }];
const departments = [{ name: 'Engineering', value: 18, fill: '#d9a857' }, { name: 'S&T', value: 13, fill: '#6c9b92' }, { name: 'TRD', value: 11, fill: '#b1723f' }];
function Panel({ eyebrow, title, children }) { return <article className="panel"><div className="panel-heading"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div></div>{children}</article>; }
function Table({ rows, columns }) { return <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column}>{row[column.toLowerCase().replaceAll(' ', '_')] ?? '-'}</td>)}</tr>)}</tbody></table></div>; }
export function Maintenance() { const [tasks, setTasks] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { operationsApi.tasks({ page: 1, limit: 20 }).then((response) => setTasks(response.data.data?.items || [])).catch(() => setTasks([])).finally(() => setLoading(false)); }, []); return <Page title="Maintenance demand" eyebrow="DEMAND REGISTER">{loading ? <Loading /> : <><div className="toolbar"><input placeholder="Search tasks" aria-label="Search tasks" /><select aria-label="Department filter"><option>All departments</option><option>Engineering</option><option>S&T</option><option>TRD</option></select><button className="primary">Export CSV</button></div><Table rows={tasks} columns={['id', 'department', 'corridor_id', 'severity', 'status']} /></>}</Page>; }
export function CandidatePlans() { return <Page title="Candidate plans" eyebrow="PLANNING RUN / NDLS-KKDE"><div className="metric-grid"><Metric label="Plan A" value="18.4 min" note="Recommended GATI" /><Metric label="Plan B" value="22.1 min" note="Higher coverage" /><Metric label="Plan C" value="26.7 min" note="Lowest possession" /></div><Panel eyebrow="DECISION EVIDENCE" title="Compare alternatives"><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={riskData}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#183b3a" /></BarChart></ResponsiveContainer></div></Panel></Page>; }
export function SimulationResults() { return <Page title="Simulation results" eyebrow="1,000 SEEDED SCENARIOS"><Panel eyebrow="DELAY DISTRIBUTION" title="Plan A resilience"><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={riskData}><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#b1723f" /></BarChart></ResponsiveContainer></div></Panel></Page>; }
export function RiskDashboard() { return <Page title="Risk dashboard" eyebrow="OPERATIONAL RISK"><div className="workspace"><Panel eyebrow="TAIL RISK" title="Delay measures"><div className="risk-list"><Metric label="Mean delay" value="18 min" note="Typical scenario" /><Metric label="P95 delay" value="41 min" note="Bad-day threshold" /><Metric label="Cascade probability" value="6.2%" note="Within policy" /></div></Panel><Panel eyebrow="WORK MIX" title="Department coverage"><div className="pie"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={departments} dataKey="value" nameKey="name" innerRadius={55} outerRadius={88}>{departments.map((entry) => <Cell key={entry.name} fill={entry.fill} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div></Panel></div></Page>; }
export function GatiDashboard() { return <Page title="GATI dashboard" eyebrow="GUARANTEED AVAILABILITY THROUGH INTELLIGENCE"><section className="hero"><div><p className="eyebrow">RECOMMENDED PLAN / A</p><h2>18.4 minutes</h2><p>Lowest combined typical and tail delay across the current candidate set.</p></div><div className="signal">60% mean impact<br />40% tail-risk penalty</div></section></Page>; }
export function Reports() {
  const reports = ['Daily report', 'Weekly report', 'Monthly report', 'Risk report', 'Maintenance report', 'Simulation report', 'Executive report'];
  const [downloading, setDownloading] = useState(''); const [toast, setToast] = useState(null);
  async function download(name) {
    const type = name.replace(' report', ''); setDownloading(name); setToast(null);
    try {
      const response = await operationsApi.downloadReport(type);
      const url = URL.createObjectURL(new Blob([response.data], { type: 'text/csv;charset=utf-8' }));
      const link = document.createElement('a'); link.href = url; link.download = `railvista-${type}-report.csv`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url);
      setToast({ message: `${name} downloaded.` });
    } catch (error) { setToast({ message: error.response?.data?.detail || `Unable to download ${name}.`, error: true }); }
    finally { setDownloading(''); }
  }
  return <Page title="Reports" eyebrow="OPERATIONAL REPORTING">{toast && <div className={`workflow-toast ${toast.error ? 'error' : ''}`} role="status">{toast.message}</div>}<div className="report-grid">{reports.map((name) => <article className="metric" key={name}><p>{name}</p><strong>{downloading === name ? 'Generating…' : 'Ready'}</strong><button className="primary" disabled={Boolean(downloading)} onClick={() => download(name)}>{downloading === name ? 'Preparing…' : 'Download'}</button></article>)}</div></Page>;
}
export function Notifications() { return <Page title="Notifications" eyebrow="ALERT CENTER"><Panel eyebrow="LATEST" title="Operational notifications"><div className="watch-row"><span className="watch-icon amber">!</span><div><strong>High risk scenario detected</strong><small>Plan A exceeds the rain-overrun threshold in 6.2% of simulations.</small></div></div><div className="watch-row"><span className="watch-icon green">+</span><div><strong>Simulation completed</strong><small>Planning run for NDLS-KKDE is ready for review.</small></div></div></Panel></Page>; }
export function Administration({ title = 'Administration' }) { const [dataset, setDataset] = useState(null); useEffect(() => { operationsApi.datasetStatus().then((response) => setDataset(response.data.data)).catch(() => setDataset(null)); }, []); const rows = dataset ? [{ id: 'maintenance', record_type: 'Maintenance records', count: dataset.maintenance }, { id: 'network', record_type: 'Network records', count: dataset.network }, { id: 'stations', record_type: 'Station records', count: dataset.stations }, { id: 'trains', record_type: 'Train records', count: dataset.trains }, { id: 'scenarios', record_type: 'Scenario records', count: dataset.scenarios }] : []; return <Page title={title} eyebrow="GOVERNANCE"><Panel eyebrow="SYNTHETIC DATASET" title="Dataset status">{dataset ? <><div className="metric-grid"><Metric label="Seed status" value={dataset.seedStatus} note={dataset.lastImportAt ? `Last import ${new Date(dataset.lastImportAt).toLocaleString('en-IN')}` : 'No import recorded'} /></div><Table rows={rows} columns={['record_type', 'count']} /></> : <Loading />}</Panel><Panel eyebrow="ACCESS CONTROL" title="Managed identities"><Table rows={[{ id: 'usr-001', name: 'Control Officer', role: 'CONTROL_OFFICER', status: 'Active' }]} columns={['id', 'name', 'role', 'status']} /></Panel></Page>; }
export function Profile() { return <Page title="Profile" eyebrow="ACCOUNT"><Panel eyebrow="IDENTITY" title="Control Officer"><div className="profile-fields"><label>Name<input value="Control Officer" readOnly /></label><label>Email<input value="control@railvista.local" readOnly /></label><label>Role<input value="CONTROL_OFFICER" readOnly /></label></div></Panel></Page>; }
export function Settings() { return <Page title="Settings" eyebrow="SYSTEM PREFERENCES"><Panel eyebrow="PLANNING POLICY" title="Run configuration"><div className="profile-fields"><label>Default scenarios<input value="1000" readOnly /></label><label>Active calibration<input value="calibration-v1" readOnly /></label><label>Timezone<input value="Asia/Kolkata" readOnly /></label></div></Panel></Page>; }
function Page({ title, eyebrow, children }) { return <main className="content"><header><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div></header><section className="operations-content">{children}</section></main>; }
function Metric({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
function Loading() { return <motion.div className="loading-state" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><span className="loading-tracks"><i /><i /><i /></span><div><strong>Loading operational data...</strong><p>Fetching the latest authorized snapshot.</p></div></motion.div>; }
