import { AnimatePresence, motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../../context/AuthContext.jsx';
import { operationsApi } from '../../api/operationsApi.js';
import { RailNetworkMap } from '../../components/network/RailNetworkMap.jsx';

const pipeline = [['Maintenance Requests', 'maintenance'], ['RiskClock', 'priority'], ['Priority Engine', 'priority'], ['Block Bundler', 'planning'], ['Conflict Shield', 'planning'], ['CP-SAT Optimization', 'planning'], ['Monte Carlo Simulation', 'planning'], ['GATI Evaluation', 'planning'], ['Final Recommended Plan', 'approval']];
const routes = { maintenance: '/maintenance', priority: '/intelligence/priority', planning: '/intelligence/optimization', approval: '/workflow/final-plan' };
const clamp = (value, max = 100) => Math.max(0, Math.min(max, value));

function Metric({ label, value, note, tone = 'blue' }) { return <motion.article className="metric" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} whileHover={{ y: -3 }} transition={{ duration: .24 }}><p>{label}</p><strong>{value}</strong><small><span className={`signal-dot overview-dot ${tone}`} />{note}</small></motion.article>; }
function Panel({ eyebrow, title, children, action }) { return <article className="panel"><div className="panel-heading"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div>{action}</div>{children}</article>; }

export function Dashboard() {
  const { session } = useAuth();
  const [state, setState] = useState({ loading: true, data: null });
  const [selectedAction, setSelectedAction] = useState('');
  useEffect(() => { let mounted = true; operationsApi.workflowOverview().then((response) => mounted && setState({ loading: false, data: response.data.data })).catch(() => mounted && setState({ loading: false, data: null })); return () => { mounted = false; }; }, []);
  const summary = useMemo(() => {
    const data = state.data; const tasks = data?.tasks || []; const plans = data?.plans || [];
    const recommended = plans.slice().sort((a, b) => (a.metrics?.gati ?? Infinity) - (b.metrics?.gati ?? Infinity))[0];
    const highRisk = tasks.filter((task) => task.severity >= 4 && task.status !== 'COMPLETED').length;
    const sections = new Set(tasks.map((task) => task.sectionId || task.assetId));
    const bundles = [...sections].filter((section) => tasks.filter((task) => (task.sectionId || task.assetId) === section).length > 1).length;
    const conflicts = Math.max(0, tasks.length - sections.size - bundles);
    const gatiValues = plans.map((plan) => plan.metrics?.gati).filter(Number.isFinite);
    return { data, tasks, plans, recommended, highRisk, bundles, conflicts, averageGati: gatiValues.length ? (gatiValues.reduce((sum, value) => sum + value, 0) / gatiValues.length).toFixed(1) : '—', confidence: recommended ? clamp(Math.round(88 + Math.min(10, plans.length * 2) - highRisk / 8)) : 0, reduction: recommended?.metrics?.meanDelay != null ? `${Math.max(1, Math.round(recommended.metrics.meanDelay * .18))} min` : '—', emergencyAlerts: tasks.filter((task) => task.season === 'Monsoon' || task.overdueDays > 0).length };
  }, [state.data]);
  const activity = [summary.tasks.length ? { icon: '✓', title: `${summary.tasks.length} maintenance requests synchronized`, note: 'Maintenance register · just now', tone: 'green' } : { icon: '…', title: 'Awaiting maintenance data', note: 'Import a dataset to begin', tone: 'amber' }, summary.highRisk ? { icon: '!', title: `${summary.highRisk} high-risk assets flagged by RiskClock`, note: 'Severity, weather and due-date signals', tone: 'amber' } : { icon: '✓', title: 'RiskClock has no critical open alerts', note: 'Current corridor state', tone: 'green' }, summary.recommended ? { icon: 'AI', title: `${summary.recommended.name} is the current recommendation`, note: `GATI ${summary.recommended.metrics?.gati ?? '—'} · candidate ranking updated`, tone: 'blue' } : { icon: 'AI', title: 'No candidate plan has been generated', note: 'Open Trade-off Dial to run CP-SAT', tone: 'blue' }, { icon: '◈', title: `${summary.data?.activeBlocks ?? 0} possession blocks under watch`, note: 'Approved, published, or executing plans', tone: 'blue' }];
  const actions = [['Analyze Network', '/network'], ['Generate Candidate Plans', '/intelligence/trade-offs'], ['Run Simulation', '/intelligence/simulation'], ['Compare Plans', '/plans'], ['Approve Final Plan', '/workflow/approval']];
  return <main className="content">
    <style>{`.overview-ghost{display:inline-flex;align-items:center;text-decoration:none}.overview-dot{width:6px;height:6px;margin-right:6px;box-shadow:none}.overview-dot.green{background:#35bd88}.overview-dot.amber{background:#e5a94a}.overview-recommendation-grid,.overview-status-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:16px}.overview-recommendation-grid span,.overview-status-grid span{display:grid;gap:4px;padding:9px;border:1px solid #deebf4;border-radius:8px;background:#f8fcff;color:#70869a;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.04em}.overview-recommendation-grid b,.overview-status-grid b{overflow:hidden;color:#214b70;font-size:13px;text-overflow:ellipsis;text-transform:none;white-space:nowrap}.overview-pipeline{display:grid;gap:6px;margin-top:16px}.overview-pipeline>div{display:grid;grid-template-columns:24px minmax(0,1fr) 20px;align-items:center;gap:9px;color:#50708b;font-size:12px;font-weight:700}.overview-pipeline a{overflow:hidden;color:inherit;text-decoration:none;text-overflow:ellipsis;white-space:nowrap}.overview-pipeline a:hover{color:#147ac1}.pipeline-check{display:grid;width:22px;height:22px;place-items:center;border-radius:50%;background:#e8eff5;color:#71869a;font-size:10px}.pipeline-check.complete{background:#dcf4e7;color:#16714f}.pipeline-line{height:2px;background:#dce8f1}.pipeline-line.complete{background:#55b98e}.overview-timeline{display:grid;gap:0;margin-top:12px}.overview-timeline>div{display:flex;align-items:center;gap:11px;padding:12px 0;border-top:1px solid #dbe7f1}.overview-timeline>div:first-child{border-top:0}.overview-timeline .watch-icon{font-size:9px}.overview-timeline strong,.overview-timeline small{display:block}.overview-timeline strong{color:#31536f;font-size:12px}.overview-timeline small{margin-top:3px;color:#71869b;font-size:10px}.overview-insights{display:grid;gap:10px;margin-top:16px}.overview-insights p{margin:0;padding:11px 12px;border-left:3px solid #66b8ea;border-radius:0 8px 8px 0;background:#f1f8fd;color:#5e7890;font-size:12px;line-height:1.55}.overview-insights strong{color:#23527a}.overview-actions .primary{text-decoration:none}@media(max-width:520px){.overview-recommendation-grid,.overview-status-grid{grid-template-columns:1fr}.overview-pipeline>div{grid-template-columns:24px minmax(0,1fr) 12px}}`}</style>
    <header><div><p className="eyebrow">NETWORK CONTROL / LIVE OPERATIONS</p><h1>Good morning, {session?.name || 'Control Officer'}</h1></div><div className="header-user">{session?.role || 'CONTROL_OFFICER'} <span className="avatar">CO</span></div></header>
    <section className="hero control-hero"><div><p className="eyebrow">AI-POWERED RAILWAY COMMAND CENTER / {summary.data?.corridorId || 'CONNECTING'}</p><h2>One possession. Three departments. Clear decisions.</h2><p>Watch operational risk, block opportunities, plan resilience, and approval readiness from one live control surface.</p><div className="toolbar"><Link className="primary" to="/workflow">Open decision pipeline <span>→</span></Link><Link className="ghost overview-ghost" to="/intelligence">View AI intelligence</Link></div></div><div className="signal"><span className="signal-dot" />{state.loading ? 'Synchronizing control data' : state.data ? 'Network telemetry live' : 'Demo-safe operating view'}<p>{summary.data ? `${summary.data.activeBlocks} active blocks • ${summary.highRisk} risk alerts` : 'Backend data unavailable; metrics will populate when connected.'}</p></div></section>
    <section className="metric-grid control-kpis"><Metric label="High risk assets" value={summary.highRisk} note="RiskClock attention" tone={summary.highRisk ? 'amber' : 'green'} /><Metric label="Active blocks" value={summary.data?.activeBlocks ?? '—'} note="Possession watch" /><Metric label="Bundled jobs" value={summary.bundles} note="Same-section opportunities" tone="green" /><Metric label="Conflicts resolved" value={summary.plans.length ? summary.conflicts : '—'} note="Constraint-screened" tone="green" /><Metric label="Average GATI" value={summary.averageGati} note="Candidate resilience" /><Metric label="Emergency alerts" value={summary.emergencyAlerts} note="Weather or overdue work" tone={summary.emergencyAlerts ? 'amber' : 'green'} /></section>
    <section className="dashboard-map-grid"><RailNetworkMap tasks={summary.tasks} activeBlocks={summary.data?.activeBlocks || 0} /><Panel eyebrow="AI RECOMMENDATION" title="Recommended control plan" action={<span className={`stage-status ${summary.recommended?.status?.toLowerCase() || 'pending'}`}>{summary.recommended?.status || 'AWAITING RUN'}</span>}><div className="gati-orb"><strong>{summary.recommended?.metrics?.gati ?? '—'}</strong><span>GATI minutes</span></div><div className="signal-meter"><span>Decision confidence</span><i><b style={{ width: `${summary.confidence}%` }} /></i><strong>{summary.recommended ? `${summary.confidence}% confidence` : 'Run planning to score candidates'}</strong></div><div className="overview-recommendation-grid"><span>Recommended plan <b>{summary.recommended?.name || 'No plan yet'}</b></span><span>Delay reduction <b>{summary.reduction}</b></span><span>Bundled maintenance <b>{summary.bundles}</b></span><span>Risk level <b>{summary.highRisk > 3 ? 'Elevated' : summary.highRisk ? 'Watch' : 'Controlled'}</b></span></div></Panel></section>
    <section className="workspace"><Panel eyebrow="LIVE AI DECISION PIPELINE" title="From demand to approved possession" action={<Link className="workflow-next" to="/intelligence">Open AI workspace →</Link>}><div className="overview-pipeline">{pipeline.map(([label, stateKey], index) => { const complete = stateKey === 'maintenance' ? summary.tasks.length > 0 : stateKey === 'priority' ? summary.tasks.some((task) => task.priorityScore != null) : stateKey === 'planning' ? summary.plans.length > 0 : Boolean(summary.recommended); return <motion.div key={label} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .045 }}><span className={complete ? 'pipeline-check complete' : 'pipeline-check'}>{complete ? '✓' : index + 1}</span><Link to={routes[stateKey]}>{label}</Link><i className={complete ? 'pipeline-line complete' : 'pipeline-line'} /></motion.div>; })}</div></Panel><Panel eyebrow="PLANNING RUN STATUS" title="Current operational snapshot"><div className="overview-status-grid"><span>Total requests <b>{summary.tasks.length}</b></span><span>Bundled jobs <b>{summary.bundles}</b></span><span>Conflicts <b>{summary.conflicts}</b></span><span>Candidate plans <b>{summary.plans.length}</b></span><span>Simulation status <b>{summary.plans.length ? 'Complete' : 'Pending'}</b></span><span>Current best plan <b>{summary.recommended?.name || '—'}</b></span></div></Panel></section>
    <section className="workspace"><Panel eyebrow="LIVE ACTIVITY" title="Planning event timeline"><div className="overview-timeline">{activity.map((event, index) => <motion.div key={event.title} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .08 }}><span className={`watch-icon ${event.tone}`}>{event.icon}</span><div><strong>{event.title}</strong><small>{event.note}</small></div></motion.div>)}</div></Panel><Panel eyebrow="AI INSIGHTS" title="Recommended next moves"><div className="overview-insights"><p><strong>{summary.highRisk ? 'Prioritize high-risk work.' : 'Risk posture is controlled.'}</strong> {summary.highRisk ? `Focus on ${summary.highRisk} RiskClock alerts before opening further possessions.` : 'Keep monitoring incoming maintenance demand.'}</p><p><strong>{summary.bundles ? `${summary.bundles} bundle opportunities detected.` : 'Check block compatibility.'}</strong> Combine compatible department work in one possession to reduce corridor disruption.</p><p><strong>{summary.recommended ? 'Recommendation available.' : 'A candidate plan is needed.'}</strong> {summary.recommended ? `Review ${summary.recommended.name} before approval; its GATI is ${summary.recommended.metrics?.gati ?? 'not available'}.` : 'Generate candidates to compare delay and tail-risk trade-offs.'}</p></div></Panel></section>
    <section className="operations-content"><Panel eyebrow="QUICK ACTIONS" title="Control room actions"><div className="toolbar overview-actions">{actions.map(([label, to]) => <Link key={label} className="primary" to={to} onClick={() => setSelectedAction(label)}>{label}</Link>)}</div><AnimatePresence>{selectedAction && <motion.p className="muted" initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>Opening {selectedAction}…</motion.p>}</AnimatePresence></Panel></section>
  </main>;
}
