import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { operationsApi } from '../../api/operationsApi.js';

export function BlockBundler() {
  const [state, setState] = useState({ loading: true, error: '', data: null });
  const [selectedId, setSelectedId] = useState('');
  useEffect(() => { operationsApi.bundler().then((response) => { const data = response.data.data; setState({ loading: false, error: '', data }); setSelectedId(data.bundles[0]?.bundle_id || ''); }).catch((error) => setState({ loading: false, error: error.response?.data?.detail || 'Bundle candidates could not be generated.', data: null })); }, []);
  const selected = useMemo(() => state.data?.bundles.find((bundle) => bundle.bundle_id === selectedId), [state.data, selectedId]);
  return <main className="content"><nav className="breadcrumb"><Link to="/">Control center</Link><span>/</span><Link to="/workflow">Workflow</Link><span>/</span><strong>Block bundler</strong></nav><header><div><p className="eyebrow">CROSS-DEPARTMENT COORDINATION</p><h1>Block bundler</h1><p className="muted bundler-subtitle">Coordinate compatible maintenance into candidate shared possessions</p></div></header><section className="operations-content">
    {state.loading && <div className="skeleton-stack"><i /><i /><i /></div>}
    {state.error && <div className="workflow-message error-state"><strong>Bundle data is unavailable</strong><p>{state.error}</p></div>}
    {state.data && <div className="bundler-content"><div className="metric-grid bundler-kpis"><Metric label="Bundle candidates" value={state.data.summary.bundleCandidates} note="Authoritative bundler output" /><Metric label="Multi-department" value={state.data.summary.multiDepartmentBundles} note="Coordinated work groups" /><Metric label="Tasks bundled" value={state.data.summary.tasksBundled} note="Participating maintenance work" /><Metric label="Potential requests avoided" value={state.data.summary.potentialBlockRequestsAvoided} note="Candidate, before optimization" /></div>
      {!state.data.bundles.length ? <div className="workflow-message"><strong>No compatible multi-department bundle candidates were produced.</strong><p>The bundler requires same-section work, overlapping task windows, and distinct department resources.</p></div> : <div className="bundler-workspace">
        <section className="workspace bundler-top"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">DEPARTMENT COORDINATION</p><h3>Generated cross-department combinations</h3></div><span className="evidence-source">Bundler output</span></div><div className="bundler-combinations">{state.data.departmentCombinations.map((item) => <div key={item.label}><strong>{item.label}</strong><span>{item.bundles} candidate {item.bundles === 1 ? 'bundle' : 'bundles'}</span></div>)}</div></article><article className="panel bundler-flow"><p className="eyebrow">OPTIMIZATION HANDOFF</p><h3>Bundle passed to CP-SAT as solver unit</h3><div className="bundler-flow-steps"><strong>Prioritized maintenance</strong><i>↓</i><strong>Compatibility check</strong><i>↓</i><strong>Shared bundle</strong><i>↓</i><strong>Operational constraints</strong><i>↓</i><strong>CP-SAT</strong></div><p>Parallel department work uses the bundle’s maximum task duration, rather than the sum of durations.</p></article></section>
        <article className="panel"><div className="panel-heading"><div><p className="eyebrow">BUNDLE CANDIDATES</p><h3>Compatible same-section maintenance work</h3></div><span className="status">{state.data.corridorId}</span></div><div className="table-wrap bundler-table"><table><thead><tr><th>Bundle</th><th>Section</th><th>COA window</th><th>Tasks</th><th>Departments</th><th>Required duration</th><th>Priority</th><th>Operational status</th></tr></thead><tbody>{state.data.bundles.map((bundle) => <tr key={bundle.bundle_id} onClick={() => setSelectedId(bundle.bundle_id)} className={selected?.bundle_id === bundle.bundle_id ? 'selected' : ''}><td><strong>{bundle.bundle_id}</strong></td><td>{bundle.section_id}</td><td>{bundle.selectedWindow?.id || 'No fitting window'}</td><td>{bundle.tasks_combined}</td><td>{bundle.departments.join(' + ')}</td><td>{bundle.after_block_minutes} min</td><td>{bundle.members.some((task) => task.priorityScore != null) ? Math.max(...bundle.members.map((task) => task.priorityScore ?? 0)).toFixed(1) : 'Not scored'}</td><td><span className={`risk-pill ${bundle.operationalStatus === 'FEASIBLE' ? 'available' : bundle.operationalStatus === 'TRAIN CONFLICT' ? 'blocked' : 'restricted'}`}>{bundle.operationalStatus}</span></td></tr>)}</tbody></table></div></article>
        {selected && <section className="workspace bundler-detail"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">SELECTED BUNDLE</p><h3>{selected.bundle_id} · {selected.section_id}</h3></div><span className={`risk-pill ${selected.operationalStatus === 'FEASIBLE' ? 'available' : selected.operationalStatus === 'TRAIN CONFLICT' ? 'blocked' : 'restricted'}`}>{selected.operationalStatus}</span></div><div className="bundler-member-list">{selected.members.map((task) => <div key={task.id}><strong>{task.department}</strong><span>{task.sourceId} · {task.defectType}</span><small>{task.durationMin} min · Priority {task.priorityScore == null ? 'not scored' : task.priorityScore.toFixed(1)}</small></div>)}</div><div className="bundler-stats"><span>Independent work<b>{selected.before_block_minutes} min</b></span><span>Shared block<b>{selected.after_block_minutes} min</b></span><span>Potential avoided<b>{selected.block_time_saved_minutes} min</b></span></div></article><article className="panel"><p className="eyebrow">COMPATIBILITY & OPERATIONAL EVIDENCE</p><h3>Why these tasks were bundled</h3><div className="bundler-evidence"><span>✓ Same section: <b>{selected.section_id}</b></span><span>✓ Overlapping task window: <b>{selected.window.start_min}–{selected.window.end_min} min</b></span><span>✓ Distinct department resources: <b>{selected.departments.join(', ')}</b></span><span>✓ Parallel-work duration: <b>{selected.after_block_minutes} min</b></span>{selected.selectedWindow ? <><span>✓ Candidate COA: <b>{selected.selectedWindow.id} · {selected.selectedWindow.durationMin} min</b></span><span>{selected.selectedWindow.trainFeasibility === 'TRAIN SAFE' ? '✓' : '!'} Train check: <b>{selected.selectedWindow.trainFeasibility}</b></span><span>COA status: <b>{selected.selectedWindow.status}</b></span><span>Block utilization: <b>{selected.utilizationPercent}%</b></span></> : <span>! No persisted COA window fits the combined task time and duration.</span>}</div></article></section>}
      </div>}
      <Link className="workflow-next" to="/workflow/conflict-shield">Continue to Conflict Shield →</Link>
    </div>}
  </section></main>;
}
function Metric({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
