import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { operationsApi } from '../../api/operationsApi.js';

const name = (value) => ({ ENGINEERING: 'Engineering', SNT: 'S&T', TRD: 'TRD' }[value] || value);
const mins = (value) => `${String(Math.floor((value || 0) / 60)).padStart(2, '0')}:${String((value || 0) % 60).padStart(2, '0')}`;
function Shell({ children }) { return <main className="content"><div className="breadcrumb"><span>Control center</span><span>/</span><span>Workflow</span><span>/</span><strong>Block planning</strong></div><header><div><p className="eyebrow">WORKFLOW STAGE</p><h1>Block planning</h1></div></header><section className="operations-content">{children}</section></main>; }
function Kpi({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }

export function BlockPlanning() {
  const [state, setState] = useState({ loading: true, error: '', data: null }); const [selectedWindow, setSelectedWindow] = useState(null);
  useEffect(() => { let active = true; operationsApi.blockPlanning().then((response) => active && setState({ loading: false, error: '', data: response.data.data })).catch(() => active && setState({ loading: false, error: 'Unable to load block planning workspace.', data: null })); return () => { active = false; }; }, []);
  const data = state.data; const windows = data?.windows || [];
  useEffect(() => { if (windows.length && !windows.some((window) => window._id === selectedWindow)) setSelectedWindow(windows[0]._id); }, [windows, selectedWindow]);
  const selected = windows.find((window) => window._id === selectedWindow) || windows[0];
  const inputs = useMemo(() => data ? [['COA availability', data.windows.length, data.windows.length ? 'ACTIVE' : 'UNAVAILABLE'], ['Train timetable', data.trains.length, data.trains.length ? 'ACTIVE' : 'UNAVAILABLE'], ['Goods forecast', data.goods.length, data.goods.length ? 'ACTIVE' : 'UNAVAILABLE'], ['Network capacity', data.network.length, data.network.length ? 'ACTIVE' : 'UNAVAILABLE'], ['Department resources', data.resources.length, data.resources.length ? 'ACTIVE' : 'UNAVAILABLE'], ['Asset context', data.assets.length, data.assets.length ? 'INFORMATIONAL' : 'UNAVAILABLE']] : [], [data]);
  if (state.loading) return <Shell><div className="skeleton-stack"><i /><i /><i /></div></Shell>;
  if (state.error) return <Shell><div className="workflow-message error-state"><strong>Unable to load block planning workspace.</strong><p>Planning inputs could not be retrieved.</p></div></Shell>;
  const priorityTasks = data.priorityTasks || []; const bundles = data.bundles || []; const conflicts = data.conflicts || []; const safe = conflicts.filter((item) => item.classification === 'SAFE').length; const unsafe = conflicts.filter((item) => item.classification === 'UNSAFE').length;
  const eligible = selected ? priorityTasks.filter((task) => (task.sectionId || task.assetId) === selected.sectionId && selected.availabilityStatus !== 'BLOCKED' && selected.endMin - selected.startMin >= task.durationMin && (selected.allowedDepartments || []).includes(task.department)).length : 0;
  return <Shell>
    <div className="riskclock-intro"><p>Coordinate maintenance demand with operational block availability</p><span>Read-only planning workspace</span></div>
    <div className="metric-grid block-kpis"><Kpi label="Priority tasks" value={priorityTasks.length} note="Persisted prioritized demand" /><Kpi label="COA windows" value={windows.length} note="Possession availability records" /><Kpi label="Coordinated bundles" value={bundles.length} note="AI bundler output" /><Kpi label="Hard conflicts" value={unsafe} note="Latest plan validation" /><Kpi label="Sections" value={data.network.length} note="Network capacity records" /><Kpi label="Resources" value={data.resources.length} note="Department capacity records" /></div>
    <article className="panel"><div className="panel-heading"><div><p className="eyebrow">PRIORITY HANDOFF</p><h3>Prioritized demand entering block planning</h3></div><span className="status">{[...new Set(priorityTasks.map((task) => task.department))].map(name).join(' · ')}</span></div><div className="block-handoff-list">{priorityTasks.slice(0, 5).map((task) => <span key={task._id}><strong>{task.sourceId}</strong>{task.sectionId || task.assetId} · {task.priorityScore.toFixed(1)}</span>)}</div></article>
    <article className="panel"><p className="eyebrow">PLANNING INPUTS</p><h3>Persisted operational inputs</h3><div className="planning-inputs">{inputs.map(([label, count, status]) => <div key={label}><small>{label}</small><strong>{count}</strong><span className={`input-status ${status.toLowerCase()}`}>{status}</span></div>)}</div></article>
    <section className="workspace block-windows"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">ELIGIBLE BLOCK WINDOWS</p><h3>COA possession availability</h3></div><span className="status">{windows.length} records</span></div>{windows.length ? <div className="table-wrap"><table className="riskclock-table"><thead><tr><th>Section</th><th>Date</th><th>Start</th><th>End</th><th>Duration</th><th>Status</th></tr></thead><tbody>{windows.slice(0, 8).map((window) => <tr key={window._id} className={window._id === selected?._id ? 'selected' : ''} onClick={() => setSelectedWindow(window._id)}><td>{window.sectionId}</td><td>{new Date(window.date).toLocaleDateString('en-IN')}</td><td>{mins(window.startMin)}</td><td>{mins(window.endMin)}</td><td>{window.endMin - window.startMin} min</td><td><span className={`risk-pill ${window.availabilityStatus.toLowerCase()}`}>{window.availabilityStatus}</span></td></tr>)}</tbody></table></div> : <p className="muted">No eligible COA windows are available.</p>}</article><article className="panel"><p className="eyebrow">WINDOW CONTEXT</p><h3>{selected ? `${selected.sectionId} · ${mins(selected.startMin)}–${mins(selected.endMin)}` : 'No window selected'}</h3>{selected && <><div className="window-context"><span>Eligible priority tasks<strong>{eligible}</strong></span><span>Allowed departments<strong>{(selected.allowedDepartments || []).map(name).join(', ') || 'Not provided'}</strong></span><span>Possession type<strong>{selected.possessionType || 'Not provided'}</strong></span></div><p className="muted">Train protection, network capacity, department resources and freight demand are passed to the optimizer when it evaluates feasibility.</p></>}</article></section>
    <section className="workspace block-bundle-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">COORDINATED BLOCK BUNDLES</p><h3>Compatible same-section work</h3></div><span className="status">Optimizer input</span></div>{bundles.length ? <div className="bundle-list">{bundles.slice(0, 4).map((bundle) => <div className="bundle-item" key={bundle.bundle_id}><strong>{bundle.bundle_id} · {bundle.section_id}</strong><span>{bundle.departments.map(name).join(' + ')}</span><small>{bundle.tasks_combined} tasks · {bundle.before_block_minutes} min independent · {bundle.after_block_minutes} min coordinated · {bundle.block_time_saved_minutes} min saved</small></div>)}</div> : <p className="muted">No compatible maintenance bundles were found.</p>}</article><article className="panel"><p className="eyebrow">CONFLICT SHIELD</p><h3>Latest persisted-plan validation</h3><div className="conflict-summary"><span><strong>{safe}</strong> SAFE</span><span><strong>{unsafe}</strong> UNSAFE</span></div>{conflicts.length ? conflicts.slice(0, 4).map((conflict, index) => <p className="conflict-line" key={index}><strong>{conflict.classification}</strong> · {conflict.type} · {conflict.section_id || 'Section unavailable'}<small>{conflict.reason}</small></p>) : <p className="muted">No persisted candidate conflict evidence is available.</p>}</article></section>
    <article className="panel"><p className="eyebrow">OPTIMIZATION READINESS</p><h3>Inputs passed to CP-SAT</h3><div className="readiness-grid">{[['Priority demand', priorityTasks.length], ['COA availability', windows.length], ['Train timetable', data.trains.length], ['Goods forecast', data.goods.length], ['Network capacity', data.network.length], ['Department resources', data.resources.length], ['Block bundles', bundles.length], ['Conflict validation', conflicts.length]].map(([label, count]) => <span key={label}><i>{count ? '✓' : '—'}</i>{label}<b>{count ? 'READY' : 'UNAVAILABLE'}</b></span>)}</div><div className="priority-handoff"><div><strong>Prioritized demand<small>Scheduling preference</small></strong><i>+</i><strong>Operational constraints<small>Feasibility</small></strong><i>+</i><strong>Bundles and validation<small>Coordinated units</small></strong><i>↓</i><strong>CP-SAT<small>Candidate plans</small></strong></div></div></article>
    <Link className="workflow-next" to="/workflow/coa">Continue to COA Integration →</Link>
  </Shell>;
}
