import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { operationsApi } from '../../api/operationsApi.js';

const time = (minutes) => `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`;

export function ConflictShield() {
  const [state, setState] = useState({ loading: true, error: '', data: null });
  const [selectedId, setSelectedId] = useState('');
  useEffect(() => { operationsApi.conflictShield().then((response) => { const data = response.data.data; setState({ loading: false, error: '', data }); setSelectedId(data.candidates.find((candidate) => candidate.result === 'CONFLICT')?.id || data.candidates[0]?.id || ''); }).catch((error) => setState({ loading: false, error: error.response?.data?.detail || 'Conflict Shield evidence could not be loaded.', data: null })); }, []);
  const selected = useMemo(() => state.data?.candidates.find((candidate) => candidate.id === selectedId), [state.data, selectedId]);
  return <main className="content"><nav className="breadcrumb"><Link to="/">Control center</Link><span>/</span><Link to="/workflow">Workflow</Link><span>/</span><strong>Conflict Shield</strong></nav><header><div><p className="eyebrow">OPERATIONAL VALIDATION</p><h1>Conflict Shield / Ripple Check</h1><p className="muted shield-subtitle">Validate bundle and possession safety before optimization</p></div></header><section className="operations-content">
    {state.loading && <div className="skeleton-stack"><i /><i /><i /></div>}
    {state.error && <div className="workflow-message error-state"><strong>Unable to run Conflict Shield</strong><p>{state.error}</p></div>}
    {state.data && <div className="shield-content"><div className="metric-grid shield-kpis"><Metric label="Candidates checked" value={state.data.summary.candidatesChecked} note="Bundle / COA candidates" /><Metric label="Conflict free" value={state.data.summary.conflictFree} note="Hard checks passed" /><Metric label="Conflicts detected" value={state.data.summary.conflictsDetected} note="Train or resource evidence" /><Metric label="Sections affected" value={state.data.summary.sectionsAffected} note="Candidate sections" /></div>
      {!state.data.candidates.length ? <div className="workflow-message"><strong>No candidates reached Conflict Shield.</strong><p>Run the normal seed and start the AI engine to generate bundle candidates.</p></div> : <div className="shield-workspace">
        <section className="workspace shield-top"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">VALIDATION PIPELINE</p><h3>Hard checks and soft operational impact</h3></div><span className="evidence-source">{state.data.safetyMarginMin} min train margin</span></div><div className="shield-pipeline"><strong>COA status</strong><i>↓</i><strong>Train protection</strong><i>↓</i><strong>Resource occupancy</strong><i>↓</i><strong>Valid / conflict</strong></div><p className="shield-note">Goods pressure is shown as a soft optimizer impact; it never changes a safety result.</p></article><article className="panel"><p className="eyebrow">RIPPLE CHECK</p><h3>{state.data.rippleCheck.status.replace('_', ' ')}</h3><p className="shield-note">{state.data.rippleCheck.detail}</p><p className="shield-note">Downstream effects remain represented only in simulation/risk services, not in Conflict Shield.</p></article></section>
        <article className="panel"><div className="panel-heading"><div><p className="eyebrow">CANDIDATE VALIDATION</p><h3>Bundle candidates with possession evidence</h3></div><span className="status">Pre-optimization review</span></div><div className="table-wrap shield-table"><table><thead><tr><th>Candidate</th><th>Section</th><th>COA</th><th>Tasks</th><th>Departments</th><th>Train check</th><th>Goods impact</th><th>Result</th></tr></thead><tbody>{state.data.candidates.map((candidate) => <tr key={candidate.id} onClick={() => setSelectedId(candidate.id)} className={selected?.id === candidate.id ? 'selected' : ''}><td><strong>{candidate.id}</strong></td><td>{candidate.sectionId}</td><td>{candidate.window?.id || 'No fitting window'}</td><td>{candidate.tasks.length}</td><td>{candidate.departments.join(' + ')}</td><td>{candidate.trainCheck}</td><td>{candidate.goodsPressure || '—'}</td><td><span className={`risk-pill ${candidate.result === 'VALID' ? 'available' : 'blocked'}`}>{candidate.result}</span></td></tr>)}</tbody></table></div></article>
        {selected && <section className="workspace shield-detail"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">SELECTED CANDIDATE EVIDENCE</p><h3>{selected.id} · {selected.sectionId}</h3></div><span className={`risk-pill ${selected.result === 'VALID' ? 'available' : 'blocked'}`}>{selected.result}</span></div><div className="shield-evidence"><span>COA check<b>{selected.coaStatus || 'No fitting COA'} · {selected.window ? 'PASS' : 'FAIL'}</b></span><span>Train check<b>{selected.trainCheck}</b></span><span>Resource check<b>{selected.resourceCheck}</b></span><span>Goods pressure<b>{selected.goodsPressure || 'No matching forecast'} · soft penalty only</b></span>{selected.window && <span>Possession<b>{time(selected.window.startMin)}–{time(selected.window.endMin)} · {selected.window.status}</b></span>}<span>Final result<b>{selected.result} · {selected.reason}</b></span></div></article><article className="panel"><p className="eyebrow">MAINTENANCE & CONFLICT EVIDENCE</p><h3>{selected.tasks.length} bundled maintenance tasks</h3><div className="shield-tasks">{selected.tasks.map((task) => <span key={task.id}><strong>{task.sourceId}</strong>{task.department} · {task.durationMin} min</span>)}</div>{selected.conflicts.length ? <div className="shield-conflicts">{selected.conflicts.map((conflict, index) => <div key={`${conflict.type}-${index}`}><strong>{conflict.type}</strong><span>{conflict.reason}</span>{conflict.train_id && <small>Protected movement: {conflict.train_id}</small>}</div>)}</div> : <p className="shield-valid">COA, train protection, and distinct resource checks passed. This evidence is advisory; the optimizer independently enforces its own hard constraints.</p>}</article></section>}
      </div>}
      <article className="panel shield-handoff"><p className="eyebrow">OPTIMIZATION HANDOFF</p><h3>Conflict Shield is annotation evidence, not a direct solver filter</h3><p>The optimizer independently removes train-conflicting choices and enforces section/resource constraints. Conflict Shield presents the same pre-optimization evidence for review.</p></article>
      <Link className="workflow-next" to="/workflow/optimization">Continue to Optimization →</Link>
    </div>}
  </section></main>;
}
function Metric({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
