import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { operationsApi } from '../../api/operationsApi.js';

const time = (minutes) => `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`;
const date = (value) => new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' });

export function GoodsForecast() {
  const [state, setState] = useState({ loading: true, error: '', data: null });
  const [selectedId, setSelectedId] = useState('');
  useEffect(() => { operationsApi.goodsForecast().then((response) => { const data = response.data.data; setState({ loading: false, error: '', data }); setSelectedId(data.forecasts[0]?.id || ''); }).catch((error) => setState({ loading: false, error: error.response?.data?.detail || 'Goods forecast evidence could not be loaded.', data: null })); }, []);
  const selected = useMemo(() => state.data?.forecasts.find((forecast) => forecast.id === selectedId), [state.data, selectedId]);
  const maxDemand = Math.max(...(state.data?.sectionPressure || []).map((item) => item.demand), 1);
  return <main className="content"><nav className="breadcrumb"><Link to="/">Control center</Link><span>/</span><Link to="/workflow">Workflow</Link><span>/</span><strong>Goods forecast</strong></nav><header><div><p className="eyebrow">FREIGHT OPERATIONS INPUT</p><h1>Goods forecast</h1><p className="muted goods-subtitle">Forecast freight pressure before allocating maintenance possessions</p></div></header><section className="operations-content">
    {state.loading && <div className="skeleton-stack"><i /><i /><i /></div>}
    {state.error && <div className="workflow-message error-state"><strong>Unable to load goods forecast</strong><p>{state.error}</p></div>}
    {state.data && <div className="goods-content"><div className="metric-grid goods-kpis"><Metric label="Forecast records" value={state.data.summary.forecastRecords} note="Persisted goods forecast" /><Metric label="Sections covered" value={state.data.summary.sectionsCovered} note="Forecast section references" /><Metric label="High pressure periods" value={state.data.summary.highPressurePeriods} note="Persisted HIGH intensity" /><Metric label="COA windows affected" value={state.data.summary.coaWindowsAffected} note="Matching section/time" /></div>
      {!state.data.forecasts.length ? <div className="workflow-message"><strong>No goods forecast records are available.</strong><p>Run the normal demo seed to import freight forecasts.</p></div> : <div className="goods-workspace">
        <section className="workspace goods-top"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">FREIGHT PRESSURE BY SECTION</p><h3>Accumulated forecast demand</h3></div><span className="evidence-source">Persisted forecast</span></div><div className="goods-bars">{state.data.sectionPressure.map((item) => <div key={item.sectionId}><strong>{item.sectionId}</strong><i><b style={{ width: `${item.demand / maxDemand * 100}%` }} /></i><span>{item.demand.toFixed(2)} demand · {item.expectedGoodsTrains} goods trains</span></div>)}</div></article><article className="panel goods-flow"><p className="eyebrow">OPTIMIZER HANDOFF</p><h3>Freight pressure is a soft penalty</h3><div className="goods-flow-steps"><strong>Goods forecast</strong><i>↓</i><strong>Section / time pressure</strong><i>↓</i><strong>Solver penalty</strong><i>↓</i><strong>CP-SAT selection</strong></div><p>High freight pressure keeps a choice feasible but makes it less preferred; train conflicts are hard feasibility checks.</p></article></section>
        <article className="panel"><div className="panel-heading"><div><p className="eyebrow">GOODS / FREIGHT FORECAST</p><h3>Persisted section and period forecasts</h3></div><span className="status">{state.data.corridorId}</span></div><div className="table-wrap goods-table"><table><thead><tr><th>Section</th><th>Date / period</th><th>Expected goods trains</th><th>Demand</th><th>Pressure</th><th>Confidence</th><th>Planning impact</th></tr></thead><tbody>{state.data.forecasts.map((forecast) => <tr key={forecast.id} onClick={() => setSelectedId(forecast.id)} className={selected?.id === forecast.id ? 'selected' : ''}><td><strong>{forecast.sectionId}</strong></td><td>{date(forecast.date)} · {time(forecast.startMin)}–{time(forecast.endMin)}</td><td>{forecast.expectedGoodsTrains}</td><td>{forecast.capacityDemand.toFixed(2)}</td><td><span className={`risk-pill ${forecast.trafficIntensity.toLowerCase() === 'high' ? 'blocked' : forecast.trafficIntensity.toLowerCase() === 'medium' ? 'restricted' : 'available'}`}>{forecast.trafficIntensity}</span></td><td>{Math.round(forecast.confidence * 100)}%</td><td>{forecast.penaltyBasis} × profile weight</td></tr>)}</tbody></table></div></article>
        <article className="panel"><div className="panel-heading"><div><p className="eyebrow">COA × FREIGHT PRESSURE</p><h3>Possessions affected by matching forecast periods</h3></div><span className="evidence-source">Soft objective input</span></div><div className="table-wrap"><table><thead><tr><th>COA window</th><th>Section</th><th>Possession</th><th>Freight forecast</th><th>Pressure</th><th>Planning impact</th></tr></thead><tbody>{state.data.forecasts.flatMap((forecast) => forecast.affectedWindows.map((window) => <tr key={`${forecast.id}-${window.id}`}><td>{window.id}</td><td>{window.sectionId}</td><td>{time(window.startMin)}–{time(window.endMin)}</td><td>{forecast.id}</td><td>{forecast.trafficIntensity} · {forecast.capacityDemand.toFixed(2)}</td><td>Feasible; penalty basis {forecast.penaltyBasis}</td></tr>))}</tbody></table></div></article>
        {selected && <section className="workspace goods-detail"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">SELECTED FORECAST EVIDENCE</p><h3>{selected.id} · {selected.sectionId}</h3></div><span className={`risk-pill ${selected.trafficIntensity.toLowerCase() === 'high' ? 'blocked' : selected.trafficIntensity.toLowerCase() === 'medium' ? 'restricted' : 'available'}`}>{selected.trafficIntensity}</span></div><div className="goods-evidence-grid"><span>Forecast period<b>{date(selected.date)} · {time(selected.startMin)}–{time(selected.endMin)}</b></span><span>Expected goods trains<b>{selected.expectedGoodsTrains}</b></span><span>Capacity demand<b>{selected.capacityDemand.toFixed(2)}</b></span><span>Confidence<b>{Math.round(selected.confidence * 100)}%</b></span><span>Affected possessions<b>{selected.affectedWindows.length}</b></span><span>Penalty basis<b>{selected.penaltyBasis}</b></span></div></article><article className="panel"><p className="eyebrow">SOLVER EFFECT</p><h3>Real objective contribution</h3><div className="goods-formula"><strong>{state.data.solver.classification}</strong><span>{state.data.solver.formula}</span></div><p className="goods-note">This forecast contributes {selected.penaltyBasis} before the active trade-off profile’s freight weight. Available profile weights are {state.data.solver.profiles.join(', ')}.</p><p className="goods-note">The optimizer only applies it to choices on {selected.sectionId} whose possession interval overlaps this forecast interval.</p></article></section>}
      </div>}
      <Link className="workflow-next" to="/workflow/bundler">Continue to Block Bundler →</Link>
    </div>}
  </section></main>;
}
function Metric({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
