import { motion } from 'framer-motion';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { planningApi } from '../../api/client.js';
import { operationsApi } from '../../api/operationsApi.js';

function useData() { const [state, setState] = useState({ loading: true, error: '', data: null }); useEffect(() => { let live = true; operationsApi.workflowOverview().then((response) => live && setState({ loading: false, error: '', data: response.data.data })).catch((error) => live && setState({ loading: false, error: error.response?.data?.detail || 'AI data is unavailable.', data: null })); return () => { live = false; }; }, []); return state; }
function Frame({ title, children }) { return <main className="content"><div className="breadcrumb"><span>Control center</span><span>/</span><span>AI intelligence</span><span>/</span><strong>{title}</strong></div><header><div><p className="eyebrow">AI DECISION INTELLIGENCE</p><h1>{title}</h1></div></header><section className="operations-content">{children}</section></main>; }
function State({ loading, error, empty, data, children }) { if (loading) return <div className="skeleton-stack"><i /><i /><i /></div>; if (error) return <div className="workflow-message error-state"><strong>Unable to load intelligence data</strong><p>{error}</p></div>; if (empty && data?.tasks?.length === 0) return <div className="workflow-message"><strong>No evaluated data yet</strong><p>{empty}</p></div>; return children; }
function Kpi({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value ?? '—'}</strong><small>{note}</small></article>; }
const DepartmentChart = ({ data }) => <div className="chart"><ResponsiveContainer><PieChart><Pie data={data} dataKey="tasks" nameKey="department" innerRadius={50} outerRadius={80}>{data.map((item, index) => <Cell key={item.department} fill={['#1c8bd4','#55b98e','#e5a94a'][index]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div>;

export function RiskClock() { const state = useData(); const tasks = state.data?.tasks || []; const departments = state.data?.departments || []; const byDue = tasks.map((task) => ({ date: new Date(task.dueAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }), risk: task.severity, urgency: task.criticality })); const overdue = tasks.filter((task) => new Date(task.dueAt) < new Date() && task.status !== 'COMPLETED').length; const risk = tasks.length ? Math.round(tasks.reduce((sum, task) => sum + task.severity, 0) / tasks.length * 20) : null; return <Frame title="RiskClock"><State {...state} empty="Import maintenance records to calculate RiskClock signals.">{<><div className="metric-grid"><Kpi label="Operational risk" value={risk == null ? null : `${risk}%`} note="Task severity index" /><Kpi label="Overdue tasks" value={overdue} note="Open work past due date" /><Kpi label="Asset health" value="—" note="Health feed not connected" /><Kpi label="Failure probability" value="—" note="Failure model not connected" /></div><div className="workspace"><article className="panel gauge-panel"><p className="eyebrow">CIRCULAR RISK GAUGE</p><div className="risk-gauge"><motion.strong initial={{ opacity: 0, scale: .85 }} animate={{ opacity: 1, scale: 1 }}>{risk == null ? '—' : `${risk}%`}</motion.strong><span>severity-based</span></div></article><article className="panel"><p className="eyebrow">RISK TREND</p><div className="chart"><ResponsiveContainer><AreaChart data={byDue}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis /><Tooltip /><Area type="monotone" dataKey="risk" stroke="#1686d1" fill="#cfeaff" /></AreaChart></ResponsiveContainer></div></article></div><article className="panel"><p className="eyebrow">DEPARTMENT-WISE RISK</p><DepartmentChart data={departments} /></article></>}</State></Frame>; }

export function PriorityEngine() { const state = useData(); const [department, setDepartment] = useState('ALL'); const [descending, setDescending] = useState(true); const tasks = useMemo(() => (state.data?.tasks || []).filter((task) => department === 'ALL' || task.department === department).sort((a, b) => descending ? (b.priorityScore ?? -1) - (a.priorityScore ?? -1) : (a.priorityScore ?? -1) - (b.priorityScore ?? -1)), [state.data, department, descending]); return <Frame title="Priority engine"><State {...state} empty="Maintenance demand is required to rank work."><div className="toolbar"><select value={department} onChange={(event) => setDepartment(event.target.value)} aria-label="Department"><option value="ALL">All departments</option><option value="ENGINEERING">Engineering</option><option value="SNT">S&T</option><option value="TRD">TRD</option></select><button className="primary" onClick={() => setDescending((value) => !value)}>Priority {descending ? 'high to low' : 'low to high'}</button></div>{tasks.length ? <div className="table-wrap"><table><thead><tr><th>Asset</th><th>Priority</th><th>Risk</th><th>Criticality</th><th>Due</th><th>Weather</th><th>Failure probability</th><th>Department</th></tr></thead><tbody>{tasks.map((task) => <tr key={task._id}><td>{task.assetId}</td><td>{task.priorityScore ?? 'Not scored'}</td><td>{task.severity}</td><td>{task.criticality}</td><td>{new Date(task.dueAt).toLocaleDateString()}</td><td>Not connected</td><td>Not connected</td><td>{task.department}</td></tr>)}</tbody></table></div> : <State empty="No tasks match this filter." />}</State></Frame>; }

export function Bundler() { const state = useData(); const groups = useMemo(() => Object.values((state.data?.tasks || []).reduce((result, task) => { const key = `${task.corridorId}:${Array.isArray(task.resources) ? task.resources.join(',') : task.resources || 'unassigned'}`; result[key] = [...(result[key] || []), task]; return result; }, {})).filter((group) => group.length > 1), [state.data]); return <Frame title="Block bundler"><State {...state} empty="Maintenance demand is required to identify compatible bundles."><div className="bundle-flow"><article className="panel"><p className="eyebrow">BEFORE BUNDLING</p><strong>{state.data.tasks.length} independent tasks</strong></article><span>→</span><article className="panel"><p className="eyebrow">AFTER BUNDLING</p><strong>{groups.length} compatible groups</strong></article></div>{groups.length ? groups.map((group, index) => <motion.article className="panel bundle-card" initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .08 }} key={group[0]._id}><strong>Bundle {index + 1}</strong><p>{[...new Set(group.map((task) => task.department))].join(' · ')} · {group.length} tasks merged</p><div className="bundle-timeline">{group.map((task) => <span key={task._id}>{task.assetId}</span>)}</div></motion.article>) : <div className="workflow-message"><strong>No compatible bundle groups</strong><p>Existing resource assignments do not yet identify a multi-task bundle.</p></div>}</State></Frame>; }

export function ConflictShield() { const state = useData(); const plans = state.data?.plans || []; return <Frame title="Conflict Shield"><State {...state} empty="Generate candidate plans before checking persisted conflicts."><div className="conflict-grid"><Kpi label="Safe blocks" value={plans.filter((plan) => plan.solver?.status === 'OPTIMAL' || plan.solver?.status === 'FEASIBLE').length} note="Solver-validated candidates" /><Kpi label="Unsafe overlaps" value="—" note="Conflict event feed not connected" /><Kpi label="Ripple effects" value="—" note="Consequence feed not connected" /><Kpi label="Resolved conflicts" value="—" note="Resolution audit not connected" /></div><article className="panel flow-panel"><span>Task demand</span><i /><span>Hard constraints</span><i /><span>Safe candidate</span></article></State></Frame>; }

export function Optimization() { const state = useData(); const plans = state.data?.plans || []; return <Frame title="CP-SAT optimization"><State {...state} empty="Run the planner to display solver candidates and objective values."><div className="plan-card-grid">{plans.map((plan) => <article className="plan-card" key={plan._id}><p className="eyebrow">{plan.name}</p><Kpi label="Solver status" value={plan.solver?.status} note="Persisted solver result" /><Kpi label="Objective" value={plan.solver?.objective} note="Optimization objective" /><Kpi label="Decision blocks" value={plan.blocks?.length} note="Candidate timeline blocks" /></article>)}</div></State></Frame>; }

export function Simulation() { const state = useData(); const [result, setResult] = useState(null); const [error, setError] = useState(''); const plan = state.data?.plans?.find((item) => item.metrics?.meanDelay != null); async function run() { if (!plan) { setError('A persisted plan with a mean delay is required before simulation.'); return; } try { setError(''); const simulation = await operationsApi.simulate({ base_delay: plan.metrics.meanDelay, count: 1000, seed: 42 }); const risk = await operationsApi.analyzeRisk(simulation.data.data.outcomes); setResult({ outcomes: simulation.data.data.outcomes, risk: risk.data.data }); } catch (requestError) { setError(requestError.response?.data?.detail || 'Simulation could not be completed.'); } } const histogram = result ? result.outcomes.filter((_, index) => index % 25 === 0).map((value, index) => ({ scenario: index * 25, delay: value })) : []; return <Frame title="Monte Carlo simulation"><State {...state} empty="A persisted plan with a mean delay is required to run a seeded simulation.">{<>{error && <div className="workflow-message error-state"><strong>Simulation failed</strong><p>{error}</p></div>}<button className="primary" onClick={run}>Run 1,000 seeded scenarios</button>{result ? <><div className="metric-grid"><Kpi label="Scenarios" value={result.risk.metrics.sample_count} note="Seed 42" /><Kpi label="Mean delay" value={result.risk.metrics.mean_delay} note="Simulated" /><Kpi label="P95" value={result.risk.metrics.p95_delay} note="Simulated" /><Kpi label="CVaR10" value={result.risk.metrics.cvar10_delay} note="Simulated" /></div><div className="panel chart"><ResponsiveContainer><BarChart data={histogram}><XAxis dataKey="scenario" /><YAxis /><Tooltip /><Bar dataKey="delay" fill="#1686d1" /></BarChart></ResponsiveContainer></div></> : <div className="workflow-message"><strong>Ready to simulate</strong><p>The AI engine will produce a reproducible delay distribution from the selected plan.</p></div>}</>}</State></Frame>; }

export function RiskAnalysis() { const state = useData(); const plans = state.data?.plans?.filter((plan) => plan.metrics?.gati != null) || []; const radar = plans.map((plan) => ({ plan: plan.name, mean: plan.metrics.meanDelay, tail: plan.metrics.cvar10, p95: plan.metrics.p95Delay })); return <Frame title="Risk analysis"><State {...state} empty="Run simulation and persist risk metrics to analyze plan resilience.">{plans.length ? <><div className="metric-grid">{['meanDelay', 'p95Delay', 'cvar10', 'cascadeProbability', 'emergencyRate'].map((key) => <Kpi key={key} label={key.replace(/([A-Z])/g, ' $1')} value={plans[0].metrics[key]} note="Recommended plan" />)}</div><div className="panel chart"><ResponsiveContainer><RadarChart data={radar}><Tooltip /><Radar dataKey="mean" stroke="#1686d1" fill="#1686d1" fillOpacity={.35} /></RadarChart></ResponsiveContainer></div></> : <State empty="No persisted risk analysis is available." />}</State></Frame>; }

export function GatiIntelligence() { const state = useData(); const ranked = (state.data?.plans || []).filter((plan) => plan.metrics?.gati != null).sort((a, b) => a.metrics.gati - b.metrics.gati); return <Frame title="GATI decision score"><State {...state} empty="Risk metrics must be persisted before plans can be ranked by GATI.">{<><article className="panel gati-formula"><p>GATI = 0.6 × Mean Delay + 0.4 × CVaR10</p><strong>{ranked[0]?.metrics.gati ?? '—'}</strong><span>Current best score</span></article><div className="panel chart"><ResponsiveContainer><BarChart data={ranked.map((plan) => ({ name: plan.name, gati: plan.metrics.gati }))}><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="gati" fill="#1686d1" /></BarChart></ResponsiveContainer></div></>}</State></Frame>; }

export function Explainability() { const state = useData(); const [question, setQuestion] = useState('Why was the selected plan recommended?'); const [answer, setAnswer] = useState(''); const [error, setError] = useState(''); const plan = state.data?.plans?.find((item) => item.metrics?.gati != null); async function ask(event) { event.preventDefault(); if (!plan) return; try { setError(''); const response = await operationsApi.explanation({ question, evidence: { plan_id: plan._id, gati: plan.metrics.gati, mean_delay: plan.metrics.meanDelay, cvar10: plan.metrics.cvar10 } }); setAnswer(response.data.data.answer); } catch (requestError) { setError(requestError.response?.data?.detail || 'Evidence explanation could not be generated.'); } } return <Frame title="Show your work"><State {...state} empty="A scored candidate plan is required for grounded explanation.">{<article className="panel chat-panel"><p className="eyebrow">READ-ONLY EVIDENCE EXPLANATION</p><h3>Ask why the recommended plan was selected</h3><form onSubmit={ask}><input value={question} onChange={(event) => setQuestion(event.target.value)} aria-label="Question" /><button className="primary">Explain decision</button></form>{error && <div className="workflow-message error-state"><p>{error}</p></div>}{answer && <div className="answer"><strong>Evidence-grounded answer</strong><p>{answer}</p></div>}</article>}</State></Frame>; }

export function TradeOff() { const state = useData(); const [weights, setWeights] = useState({ risk: 50, delay: 50, cost: 50, priority: 50, capacity: 50 }); const [notice, setNotice] = useState(''); const tasks = state.data?.tasks || []; async function optimize() { try { setNotice(''); const payload = { tasks: tasks.map((task) => ({ id: task._id, duration_min: task.durationMin, priority_score: task.priorityScore ?? task.severity * 20, resource: Array.isArray(task.resources) ? task.resources[0] : task.resources || 'track' })), windows: [{ id: 'tradeoff-window', start_min: 0, end_min: 480 }], planCount: 3, timeLimitSeconds: 30, weights }; await planningApi.generate(payload); setNotice('A fresh optimization request was submitted with the selected trade-off profile.'); } catch (requestError) { setNotice(requestError.response?.data?.detail || 'Optimization request could not be submitted.'); } } return <Frame title="Trade-off dial"><State {...state} empty="Maintenance demand is required before a fresh optimization can be requested.">{<article className="panel dial-panel">{Object.entries(weights).map(([key, value]) => <label key={key}>{key}<input type="range" min="0" max="100" value={value} onChange={(event) => setWeights({ ...weights, [key]: Number(event.target.value) })} /><strong>{value}</strong></label>)}<button className="primary" onClick={optimize}>Request fresh optimization</button>{notice && <p className="muted">{notice}</p>}</article>}</State></Frame>; }

export function IntelligencePipeline() { const steps = [['Maintenance data', '/workflow/maintenance-data'], ['RiskClock', '/intelligence/riskclock'], ['Priority', '/intelligence/priority'], ['Bundler', '/intelligence/bundler'], ['Conflict Shield', '/intelligence/conflicts'], ['CP-SAT', '/intelligence/optimization'], ['Candidate plans', '/plans'], ['Monte Carlo', '/intelligence/simulation'], ['Risk analysis', '/intelligence/risk-analysis'], ['GATI', '/intelligence/gati'], ['Gemini explanation', '/intelligence/explainability'], ['Final recommendation', '/workflow/final-plan']]; return <Frame title="Live AI pipeline"><div className="ai-pipeline">{steps.map(([label, path], index) => <motion.div initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .05 }} key={label}><span>{index + 1}</span><Link to={path}>{label}</Link></motion.div>)}</div></Frame>; }
