import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { operationsApi } from '../../api/operationsApi.js';

const band = (score) => score >= 80 ? 'Critical' : score >= 60 ? 'High' : score >= 35 ? 'Medium' : 'Low';
const source = (task) => task.sourceSystem || ({ ENGINEERING: 'TMS', SNT: 'SMMS', TRD: 'TDMS' }[task.department] || 'Unavailable');
const department = (value) => ({ ENGINEERING: 'Engineering', SNT: 'S&T', TRD: 'TRD' }[value] || value || 'Unavailable');
const factorRows = (task) => {
  const c = task.priorityFactors?.components || {};
  return [['Severity', task.severity, 5, 'defect_severity', '/ 5'], ['Criticality', task.criticality, 5, 'asset_criticality', '/ 5'], ['Overdue maintenance', task.overdueDays, 30, 'overdue_maintenance', ' days'], ['Weather condition', task.weatherFactor, 5, 'weather_condition', '/ 5'], ['Asset importance', task.assetImportance, 5, 'asset_importance', '/ 5'], ['Section importance', task.riskClock?.inputs?.sectionImportance, 5, 'track_section_importance', '/ 5'], ['Urgency', task.urgency, 5, 'urgency', '/ 5'], ['Availability impact', task.availabilityImpact, 5, 'availability_impact', '/ 5']]
    .filter(([, , , key]) => Object.prototype.hasOwnProperty.call(c, key)).map(([label, raw, max, key, suffix]) => ({ label, raw, max, suffix, contribution: c[key] }));
};
function Shell({ children }) { return <main className="content"><div className="breadcrumb"><span>Control center</span><span>/</span><span>Workflow</span><span>/</span><strong>Priority score</strong></div><header><div><p className="eyebrow">WORKFLOW STAGE</p><h1>Priority score</h1></div></header><section className="operations-content">{children}</section></main>; }
function Kpi({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }

export function PriorityScore() {
  const [state, setState] = useState({ loading: true, error: '', data: null }); const [selectedId, setSelectedId] = useState(null);
  useEffect(() => { let active = true; operationsApi.riskClock().then((response) => active && setState({ loading: false, error: '', data: response.data.data })).catch(() => active && setState({ loading: false, error: 'Unable to load priority analysis.', data: null })); return () => { active = false; }; }, []);
  const tasks = useMemo(() => (state.data?.tasks || []).filter((task) => task.priorityScore != null).sort((a, b) => b.priorityScore - a.priorityScore), [state.data]);
  useEffect(() => { if (tasks.length && !tasks.some((task) => task._id === selectedId)) setSelectedId(tasks[0]._id); }, [tasks, selectedId]);
  if (state.loading) return <Shell><div className="skeleton-stack"><i /><i /><i /></div></Shell>;
  if (state.error) return <Shell><div className="workflow-message error-state"><strong>Unable to load priority analysis.</strong><p>Priority evidence could not be retrieved.</p></div></Shell>;
  if (!tasks.length) return <Shell><div className="workflow-message"><strong>No maintenance tasks have been prioritized yet.</strong></div></Shell>;
  const selected = tasks.find((task) => task._id === selectedId) || tasks[0];
  const distribution = ['Critical', 'High', 'Medium', 'Low'].map((name) => ({ name, count: tasks.filter((task) => band(task.priorityScore) === name).length }));
  const departments = ['ENGINEERING', 'SNT', 'TRD'].map((key) => ({ key, count: tasks.filter((task) => task.department === key).length }));
  const max = Math.max(...distribution.map((item) => item.count), 1); const maxDepartment = Math.max(...departments.map((item) => item.count), 1);
  const average = (tasks.reduce((sum, task) => sum + task.priorityScore, 0) / tasks.length).toFixed(1); const components = selected.priorityFactors?.components || {};
  const evidence = [selected.priorityScore >= 60 && `Priority score is high at ${selected.priorityScore.toFixed(1)}.`, selected.criticality >= 4 && `Asset criticality is ${selected.criticality} / 5.`, selected.overdueDays > 0 && `Maintenance is ${selected.overdueDays} days overdue.`, selected.assetImportance >= 4 && `Asset importance is ${selected.assetImportance} / 5.`, Object.prototype.hasOwnProperty.call(components, 'weather_condition') && selected.weatherFactor >= 3 && `Weather condition risk is ${selected.weatherFactor} / 5.`, Object.prototype.hasOwnProperty.call(components, 'urgency') && selected.urgency >= 4 && `Urgency is ${selected.urgency} / 5.`].filter(Boolean);
  return <Shell>
    <div className="riskclock-intro"><p>Rank maintenance demand before block optimization</p><span>Authoritative priority evidence</span></div>
    <div className="metric-grid riskclock-kpis"><Kpi label="Scored tasks" value={tasks.length} note="Persisted Priority Engine scores" /><Kpi label="Critical priority" value={distribution[0].count} note="Score 80–100" /><Kpi label="High priority" value={distribution[1].count} note="Score 60–79.9" /><Kpi label="Average priority" value={average} note="Authoritative score average" /></div>
    <section className="workspace priority-top"><article className="panel"><p className="eyebrow">PRIORITY DISTRIBUTION</p><h3>Maintenance demand by priority band</h3><div className="risk-distribution">{distribution.map((item) => <div className="risk-bar" key={item.name}><span>{item.name}</span><i><b className={item.name.toLowerCase()} style={{ width: `${item.count / max * 100}%` }} /></i><strong>{item.count}</strong></div>)}</div></article><article className="panel"><p className="eyebrow">DEPARTMENT / SOURCE DISTRIBUTION</p><h3>Cross-stream maintenance demand</h3><div className="department-distribution">{departments.map((item) => <div key={item.key}><span>{department(item.key)} / {source({ department: item.key })}</span><i><b style={{ width: `${item.count / maxDepartment * 100}%` }} /></i><strong>{item.count}</strong></div>)}</div></article></section>
    <article className="panel"><div className="panel-heading"><div><p className="eyebrow">PRIORITIZED MAINTENANCE QUEUE</p><h3>Highest scheduling preference</h3></div><span className="status">Top {Math.min(tasks.length, 10)}</span></div><div className="table-wrap"><table className="riskclock-table"><thead><tr><th>Rank</th><th>Task</th><th>Source</th><th>Department</th><th>Section</th><th>RiskClock</th><th>Priority</th><th>Level</th><th>Status</th></tr></thead><tbody>{tasks.slice(0, 10).map((task, index) => <tr key={task._id} className={task._id === selected._id ? 'selected' : ''} onClick={() => setSelectedId(task._id)} tabIndex="0" onKeyDown={(event) => event.key === 'Enter' && setSelectedId(task._id)}><td>{index + 1}</td><td><strong>{task.sourceId}</strong></td><td>{source(task)}</td><td>{department(task.department)}</td><td>{task.sectionId || task.assetId || 'Unavailable'}</td><td>{task.riskClock?.score?.toFixed(1) || 'Unavailable'}</td><td>{task.priorityScore.toFixed(1)}</td><td><span className={`risk-pill ${band(task.priorityScore).toLowerCase()}`}>{band(task.priorityScore)}</span></td><td>{task.status || 'Unavailable'}</td></tr>)}</tbody></table></div></article>
    <section className="workspace priority-evidence"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">PRIORITY EVIDENCE</p><h3>{selected.sourceId} <span className="muted">· {selected.assetId}</span></h3></div><div className="risk-score"><small>PRIORITY SCORE</small><strong>{selected.priorityScore.toFixed(1)} <em>/ 100</em></strong></div></div><div className="risk-task-context"><span>{source(selected)}</span><span>{department(selected.department)}</span><span>{selected.sectionId || selected.assetId || 'Section unavailable'}</span><span>{selected.defectType || 'Maintenance type unavailable'}</span><span>RiskClock {selected.riskClock?.score?.toFixed(1) || 'Unavailable'}</span><span>{band(selected.priorityScore)} priority</span></div><div className="factor-list">{factorRows(selected).map((factor) => <div className="factor-row" key={factor.label}><div><strong>{factor.label}</strong><span>{factor.raw == null ? 'Not provided' : `${factor.raw}${factor.suffix}`}</span></div><i><b style={{ width: factor.raw == null ? '0%' : `${Math.min(100, Number(factor.raw) / factor.max * 100)}%` }} /></i><small>{factor.contribution.toFixed(1)} pts</small></div>)}</div></article><article className="panel risk-evidence"><p className="eyebrow">WHY THIS TASK HAS THIS PRIORITY</p><h3>Deterministic evidence</h3>{evidence.length ? <ul>{evidence.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="muted">No elevated individual factor is available for this task.</p>}<details><summary>Priority and RiskClock</summary><p>RiskClock answers how risky the maintenance requirement is. The Priority Engine persists the scheduling-preference score and evidence used by optimization.</p></details></article></section>
    <article className="panel priority-handoff"><p className="eyebrow">HOW PRIORITY IS USED</p><div><strong>RiskClock<small>How risky is it?</small></strong><i>↓</i><strong>Priority Engine<small>What receives preference?</small></strong><i>↓</i><strong>CP-SAT objective<small>Constraints determine feasibility.</small></strong><i>↓</i><strong>Candidate plans<small>Priority is not a scheduling guarantee.</small></strong></div><p className="muted">Higher-priority maintenance receives greater scheduling preference, subject to possession, traffic, resource, safety and other implemented constraints.</p></article>
    <Link className="workflow-next" to="/workflow/block-planning">Continue to Block Planning →</Link>
  </Shell>;
}
