import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { operationsApi } from '../../api/operationsApi.js';

const band = (score) => score == null ? 'Unavailable' : score >= 80 ? 'Critical' : score >= 60 ? 'High' : score >= 35 ? 'Medium' : 'Low';
const source = (task) => task.sourceSystem || ({ ENGINEERING: 'TMS', SNT: 'SMMS', TRD: 'TDMS' }[task.department] || 'Unavailable');
const department = (value) => ({ ENGINEERING: 'Engineering', SNT: 'S&T', TRD: 'TRD' }[value] || value || 'Unavailable');
const factorRows = (task) => {
  const components = task.riskClock?.factors?.components || {};
  return [
    ['Severity', task.severity, 5, 'defect_severity', '/ 5'], ['Criticality', task.criticality, 5, 'asset_criticality', '/ 5'],
    ['Overdue maintenance', task.overdueDays, 30, 'overdue_maintenance', ' days'], ['Weather risk', task.weatherFactor, 5, 'weather_condition', '/ 5'],
    ['Asset importance', task.assetImportance, 5, 'asset_importance', '/ 5'], ['Section importance', task.riskClock?.inputs?.sectionImportance, 5, 'track_section_importance', '/ 5'],
    ['Urgency', task.urgency, 5, 'urgency', '/ 5'], ['Availability impact', task.availabilityImpact, 5, 'availability_impact', '/ 5']
  ].filter(([, , , key]) => Object.prototype.hasOwnProperty.call(components, key))
    .map(([label, raw, max, key, suffix]) => ({ label, raw, max, suffix, contribution: components[key] }));
};
function Shell({ children }) { return <main className="content"><div className="breadcrumb"><span>Control center</span><span>/</span><span>Workflow</span><span>/</span><strong>RiskClock</strong></div><header><div><p className="eyebrow">WORKFLOW STAGE</p><h1>RiskClock</h1></div></header><section className="operations-content">{children}</section></main>; }
function Kpi({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }

export function RiskClock() {
  const [state, setState] = useState({ loading: true, error: '', data: null });
  const [selectedId, setSelectedId] = useState(null);
  useEffect(() => { let active = true; operationsApi.riskClock().then((response) => active && setState({ loading: false, error: '', data: response.data.data })).catch(() => active && setState({ loading: false, error: 'Unable to load RiskClock analysis.', data: null })); return () => { active = false; }; }, []);
  const tasks = useMemo(() => [...(state.data?.tasks || [])].sort((a, b) => (b.riskClock?.score ?? -1) - (a.riskClock?.score ?? -1)), [state.data]);
  useEffect(() => { if (tasks.length && !tasks.some((task) => task._id === selectedId)) setSelectedId(tasks[0]._id); }, [tasks, selectedId]);
  if (state.loading) return <Shell><div className="skeleton-stack"><i /><i /><i /></div></Shell>;
  if (state.error) return <Shell><div className="workflow-message error-state"><strong>Unable to load RiskClock analysis.</strong><p>The maintenance evidence could not be retrieved.</p></div></Shell>;
  if (!tasks.length) return <Shell><div className="workflow-message"><strong>No maintenance tasks are available for RiskClock analysis.</strong></div></Shell>;
  const selected = tasks.find((task) => task._id === selectedId) || tasks[0];
  const scored = tasks.filter((task) => task.riskClock?.score != null);
  const distribution = ['Critical', 'High', 'Medium', 'Low'].map((name) => ({ name, count: scored.filter((task) => band(task.riskClock.score) === name).length }));
  const max = Math.max(...distribution.map((item) => item.count), 1);
  const average = scored.length ? (scored.reduce((sum, task) => sum + task.riskClock.score, 0) / scored.length).toFixed(1) : 'Unavailable';
  const score = selected.riskClock?.score;
  const components = selected.riskClock?.factors?.components || {};
  const evidence = score == null ? [] : [selected.severity >= 4 && `Severity is ${selected.severity} / 5.`, selected.criticality >= 4 && `Asset criticality is ${selected.criticality} / 5.`, selected.overdueDays > 0 && `Maintenance is ${selected.overdueDays} days overdue.`, selected.weatherFactor >= 3 && `Weather risk is ${selected.weatherFactor} / 5.`, selected.assetImportance >= 4 && `Asset importance is ${selected.assetImportance} / 5.`, Object.prototype.hasOwnProperty.call(components, 'urgency') && selected.urgency >= 4 && `Urgency is ${selected.urgency} / 5.`, selected.riskClock.factors?.season_multiplier > 1 && `${selected.season} multiplier increased operational risk.`].filter(Boolean);
  return <Shell>
    <div className="riskclock-intro"><p>Assess maintenance risk before prioritization</p><span>Authoritative RiskClock evidence</span></div>
    <div className="metric-grid riskclock-kpis"><Kpi label="Tasks analysed" value={tasks.length} note="Open and scheduled maintenance" /><Kpi label="Critical" value={distribution[0].count} note="RiskClock 80–100" /><Kpi label="High risk" value={distribution[1].count} note="RiskClock 60–79.9" /><Kpi label="Average RiskClock" value={average} note={scored.length ? "Authoritative score average" : "No authoritative scores available"} /></div>
    <section className="workspace riskclock-top"><article className="panel"><p className="eyebrow">RISK DISTRIBUTION</p><h3>Maintenance demand by risk band</h3><div className="risk-distribution">{distribution.map((item) => <div className="risk-bar" key={item.name}><span>{item.name}</span><i><b className={item.name.toLowerCase()} style={{ width: `${item.count / max * 100}%` }} /></i><strong>{item.count}</strong></div>)}</div>{tasks.length !== scored.length && <p className="muted">${tasks.length - scored.length} task(s) have no calculated RiskClock score.</p>}</article><article className="panel riskclock-flow"><p className="eyebrow">WORKFLOW HANDOFF</p><h3>Risk evidence feeds the Priority Engine</h3><p className="muted">Scores and factor contributions are deterministic inputs to maintenance prioritization.</p><Link className="workflow-next" to="/workflow/priority">Continue to Priority →</Link></article></section>
    <article className="panel"><div className="panel-heading"><div><p className="eyebrow">TOP RISK MAINTENANCE</p><h3>Highest RiskClock scores</h3></div><span className="status">Top {Math.min(tasks.length, 8)}</span></div><div className="table-wrap"><table className="riskclock-table"><thead><tr><th>Rank</th><th>Task</th><th>Source</th><th>Department</th><th>Section</th><th>RiskClock</th><th>Level</th></tr></thead><tbody>{tasks.slice(0, 8).map((task, index) => <tr key={task._id} className={task._id === selected._id ? 'selected' : ''} onClick={() => setSelectedId(task._id)} tabIndex="0" onKeyDown={(event) => event.key === 'Enter' && setSelectedId(task._id)}><td>{index + 1}</td><td><strong>{task.sourceId}</strong></td><td>{source(task)}</td><td>{department(task.department)}</td><td>{task.sectionId || task.assetId || 'Unavailable'}</td><td>{task.riskClock?.score?.toFixed(1) || 'Not calculated'}</td><td><span className={`risk-pill ${band(task.riskClock?.score).toLowerCase()}`}>{band(task.riskClock?.score)}</span></td></tr>)}</tbody></table></div></article>
    <section className="workspace riskclock-breakdown"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">RISK FACTOR BREAKDOWN</p><h3>{selected.sourceId} <span className="muted">· {selected.assetId}</span></h3></div><div className="risk-score"><small>RISKCLOCK</small><strong>{score == null ? 'Not calculated' : <>{score.toFixed(1)} <em>/ 100</em></>}</strong></div></div><div className="risk-task-context"><span>{source(selected)}</span><span>{department(selected.department)}</span><span>{selected.sectionId || 'Section unavailable'}</span><span>{selected.defectType || 'Maintenance type unavailable'}</span></div>{score == null ? <div className="workflow-message"><strong>RiskClock factor evidence is unavailable.</strong><p>Maintenance context is shown above; no score has been invented.</p></div> : <><div className="factor-list">{factorRows(selected).map((factor) => <div className="factor-row" key={factor.label}><div><strong>{factor.label}</strong><span>{factor.raw == null ? 'Not provided' : `${factor.raw}${factor.suffix}`}</span></div><i><b style={{ width: factor.raw == null ? '0%' : `${Math.min(100, Number(factor.raw) / factor.max * 100)}%` }} /></i><small>{factor.contribution == null ? 'Unavailable' : `${factor.contribution.toFixed(1)} pts`}</small></div>)}</div><div className="season-effect"><strong>Season effect</strong><span>{selected.season || 'Other'} · {selected.riskClock.factors.season_multiplier}×</span><small>Seasonal multiplier applied by RiskClock.</small></div></>}</article><article className="panel risk-evidence"><p className="eyebrow">WHY THIS TASK IS {band(score).toUpperCase()} RISK</p><h3>Deterministic evidence</h3>{score == null ? <p className="muted">RiskClock evidence is not available for this task.</p> : evidence.length ? <ul>{evidence.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="muted">No elevated individual factor is available for this task.</p>}<details><summary>How RiskClock is calculated</summary><p>Weighted factor contributions are summed, then the authoritative seasonal multiplier is applied and capped at 100.</p></details>{score != null && <p className="evidence-source">{selected.riskClock.source === 'PERSISTED_WORKFLOW' ? 'Persisted workflow evidence' : 'Live authoritative recalculation'}</p>}</article></section>
  </Shell>;
}
