import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { operationsApi } from '../../api/operationsApi.js';

const time = (minutes) => `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`;
const date = (value) => new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' });

export function TrainTimetable() {
  const [state, setState] = useState({ loading: true, error: '', data: null });
  const [selectedId, setSelectedId] = useState('');
  useEffect(() => { operationsApi.timetable().then((response) => { const data = response.data.data; setState({ loading: false, error: '', data }); setSelectedId(data.coaChecks.find((item) => item.result === 'TRAIN CONFLICT')?.id || data.coaChecks[0]?.id || ''); }).catch((error) => setState({ loading: false, error: error.response?.data?.detail || 'Train timetable evidence could not be loaded.', data: null })); }, []);
  const selected = useMemo(() => state.data?.coaChecks.find((item) => item.id === selectedId), [state.data, selectedId]);
  const trafficMax = Math.max(...(state.data?.sectionTraffic || []).map((item) => item.movements), 1);
  return <main className="content"><nav className="breadcrumb"><Link to="/">Control center</Link><span>/</span><Link to="/workflow">Workflow</Link><span>/</span><strong>Train timetable</strong></nav><header><div><p className="eyebrow">OPERATIONAL PROTECTION</p><h1>Train timetable</h1><p className="muted timetable-subtitle">Protect train movements during maintenance block planning</p></div></header><section className="operations-content">
    {state.loading && <div className="skeleton-stack"><i /><i /><i /></div>}
    {state.error && <div className="workflow-message error-state"><strong>Unable to load timetable</strong><p>{state.error}</p></div>}
    {state.data && <div className="timetable-content"><div className="metric-grid timetable-kpis"><Metric label="Timetable records" value={state.data.summary.timetableRecords} note="Persisted train movements" /><Metric label="Sections covered" value={state.data.summary.sectionsCovered} note="Route section references" /><Metric label="Protected movements" value={state.data.summary.protectedMovements} note="High-priority services" /><Metric label="COA conflicts" value={state.data.summary.coaConflicts} note="Windows failing train check" /></div>
      {!state.data.trains.length ? <div className="workflow-message"><strong>No timetable records are available.</strong><p>Run the normal demo seed to import train movements.</p></div> : <div className="timetable-workspace">
        <section className="workspace timetable-top"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">SECTION TRAFFIC / MOVEMENT SUMMARY</p><h3>Protected movement pressure by section</h3></div><span className="evidence-source">Timetable source</span></div><div className="timetable-bars">{state.data.sectionTraffic.map((item) => <div key={item.sectionId}><strong>{item.sectionId}</strong><i><b style={{ width: `${item.movements / trafficMax * 100}%` }} /></i><span>{item.movements} movements</span></div>)}</div></article><article className="panel timetable-flow"><p className="eyebrow">PLANNING HANDOFF</p><h3>Train safety is a hard constraint</h3><div className="timetable-flow-steps"><strong>COA window</strong><i>+</i><strong>Train timetable</strong><i>+</i><strong>{state.data.safetyMarginMin} min margin</strong><i>↓</i><strong>Operational feasibility</strong><i>↓</i><strong>CP-SAT</strong></div><p>Train-conflicting scheduling choices are removed from the feasible search space.</p></article></section>
        <article className="panel"><div className="panel-heading"><div><p className="eyebrow">PROTECTED TRAIN MOVEMENTS</p><h3>Persisted timetable records</h3></div><span className="status">{state.data.corridorId}</span></div><div className="table-wrap"><table><thead><tr><th>Train</th><th>Route / sections</th><th>Departure</th><th>Arrival</th><th>Duration</th><th>Planning impact</th></tr></thead><tbody>{state.data.trains.map((train) => <tr key={train.id}><td><strong>{train.id}</strong></td><td>{train.route.join(' → ')}</td><td>{time(train.departureMin)}</td><td>{time(train.arrivalMin)}</td><td>{train.durationMin} min</td><td><span className={`risk-pill ${train.priority === 'high' ? 'restricted' : 'available'}`}>{train.priority === 'high' ? 'PROTECTED' : 'TIMETABLED'}</span></td></tr>)}</tbody></table></div></article>
        <article className="panel"><div className="panel-heading"><div><p className="eyebrow">COA × TRAIN CONFLICT CHECK</p><h3>Persisted possessions evaluated against protected movements</h3></div><span className="evidence-source">{state.data.safetyMarginMin} min safety margin</span></div><div className="table-wrap timetable-checks"><table><thead><tr><th>COA window</th><th>Section</th><th>Possession</th><th>COA status</th><th>Conflicting train(s)</th><th>Safety margin</th><th>Result</th></tr></thead><tbody>{state.data.coaChecks.map((check) => <tr key={check.id} onClick={() => setSelectedId(check.id)} className={selected?.id === check.id ? 'selected' : ''}><td><strong>{check.id}</strong></td><td>{check.sectionId}</td><td>{date(check.date)} · {time(check.startMin)}–{time(check.endMin)}</td><td><span className={`risk-pill ${check.coaStatus.toLowerCase()}`}>{check.coaStatus}</span></td><td>{check.trains.length ? check.trains.map((train) => train.id).join(', ') : 'None'}</td><td>{check.safetyMarginMin} min</td><td><span className={`risk-pill ${check.result === 'SAFE' ? 'available' : 'blocked'}`}>{check.result}</span></td></tr>)}</tbody></table></div></article>
        {selected && <section className="workspace timetable-evidence"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">SELECTED OPERATIONAL EVIDENCE</p><h3>{selected.id} · {selected.sectionId}</h3></div><span className={`risk-pill ${selected.result === 'SAFE' ? 'available' : 'blocked'}`}>{selected.result}</span></div><div className="timetable-evidence-grid"><span>COA status<b>{selected.coaStatus}</b></span><span>Possession<b>{time(selected.startMin)}–{time(selected.endMin)}</b></span><span>Safety protection<b>{selected.safetyMarginMin} min either side</b></span><span>Train feasibility<b>{selected.result === 'SAFE' ? 'SAFE FOR TRAIN CHECK' : 'UNSAFE'}</b></span></div>{selected.trains.length ? <div className="timetable-conflicts">{selected.trains.map((train) => <div key={train.id}><strong>{train.id}</strong><span>{time(train.departureMin)}–{time(train.arrivalMin)} · {train.route.join(' → ')}</span><small>Overlaps the possession after applying the {selected.safetyMarginMin}-minute protection margin.</small></div>)}</div> : <p className="timetable-safe">No protected train movement overlaps this possession after applying the configured safety margin. Other planning constraints can still apply.</p>}</article><article className="panel"><p className="eyebrow">AFFECTED ELIGIBLE WORK</p><h3>{selected.eligibleTasks.length ? 'Maintenance demand in this possession' : 'No eligible maintenance demand'}</h3>{selected.eligibleTasks.length ? <div className="timetable-tasks">{selected.eligibleTasks.map((task) => <span key={`${task.sourceId}-${task.department}`}><strong>{task.sourceId}</strong>{task.department}</span>)}</div> : <p className="muted">Task eligibility is derived from the persisted COA window and maintenance constraints.</p>}<p className="timetable-note">COA authority and train feasibility remain separate: an AVAILABLE COA window can still be unsafe around a train movement.</p></article></section>}
      </div>}
      <Link className="workflow-next" to="/workflow/goods-forecast">Continue to Goods Forecast →</Link>
    </div>}
  </section></main>;
}
function Metric({ label, value, note }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
